export interface Exercise {
  id: string;
  name: string;
  category: string;
  muscleGroup: string;
  secondaryMuscles?: string[];
  equipment: string;
  caloriesPerMinute: number;
  instructions?: string[];
  tip?: string;
  // ── Richer form-guide / programming data (D-LIFT-19) ──
  // All OPTIONAL + back-compat: existing entries omit them; surfaces render them
  // only when present, and the engines treat absence as "unknown". Backfilled
  // incrementally — see docs/lift-section-audit.md D-LIFT-19.
  /** Relative skill/coordination demand — gates how it's introduced/explained. */
  difficulty?: "beginner" | "intermediate" | "advanced";
  /** Prescribed tempo, eccentric-first e.g. "3-1-1" (down-pause-up), seconds. */
  tempo?: string;
  /** Trains the target muscle at a long muscle length (more growth per set). */
  lengthenedBias?: boolean;
  /** The usual form errors, surfaced as "watch out" cues in the guide. */
  commonMistakes?: string[];
  /** Equal-difficulty swaps (same pattern) — feeds Replace / equipment subs. */
  alternatives?: string[];
  /** Easier scalings when the movement is too hard (incline / assisted / …). */
  regressions?: string[];
  /** Demo media — start/finish/loop assets (D-LIFT-20). Full URLs or asset keys. */
  media?: string[];
}

export const EXERCISE_CATEGORIES = [
  "Chest",
  "Back",
  "Shoulders",
  "Biceps",
  "Triceps",
  "Legs",
  "Core",
  "Full Body",
  "Cardio",
] as const;

export const EXERCISES: Exercise[] = [
  // ================= CHEST =================
  {
    id: "bench-press",
    name: "Bench Press",
    category: "Chest",
    muscleGroup: "Pectorals",
    secondaryMuscles: ["Triceps", "Front Delts"],
    equipment: "Barbell",
    caloriesPerMinute: 7.5,
    instructions: [
      "Lie flat, feet planted, eyes directly under the bar.",
      "Pinch your shoulder blades hard into the bench and grip slightly wider than shoulders.",
      "Unrack, then lower the bar to your mid-chest with elbows at about 45° from your torso.",
      "Drive the bar up and slightly back over your shoulders to full lockout.",
    ],
    tip: "Flared elbows (straight out at 90°) are how shoulders get wrecked. If you can't hold the 45° tuck, drop weight and fix the groove.",
    difficulty: "intermediate",
    tempo: "2-1-1",
    commonMistakes: [
      "Flaring the elbows to 90° instead of a ~45° tuck.",
      "Bouncing the bar off the chest instead of a controlled touch.",
      "Letting the hips lift off the bench to grind a rep.",
    ],
    alternatives: ["db-bench", "incline-bench"],
    regressions: ["db-bench", "push-ups"],
  },
  {
    id: "incline-bench",
    name: "Incline Bench Press",
    category: "Chest",
    muscleGroup: "Upper Chest",
    secondaryMuscles: ["Triceps", "Front Delts"],
    equipment: "Barbell",
    caloriesPerMinute: 7.5,
    instructions: [
      "Set the bench to 30°, feet flat, eyes under the bar.",
      "Retract your shoulder blades into the pad and grip slightly wider than shoulders.",
      "Lower the bar to your upper chest, elbows tracking around 45° from your torso.",
      "Press up and slightly back, squeezing the upper chest at lockout.",
    ],
    tip: "Cranking the bench above 45° turns this into a front-delt press. Keep the incline low or you're not training upper chest.",
  },
  {
    id: "decline-bench",
    name: "Decline Bench Press",
    category: "Chest",
    muscleGroup: "Lower Chest",
    secondaryMuscles: ["Triceps", "Front Delts"],
    equipment: "Barbell",
    caloriesPerMinute: 7.5,
    instructions: [
      "Lock your feet in, pinch shoulder blades, grip slightly wider than shoulders.",
      "Unrack with a tight brace and stack the bar over your lower chest.",
      "Lower with control until the bar lightly touches your lower chest.",
      "Press up and slightly back, finishing with elbows stacked over shoulders.",
    ],
  },
  {
    id: "db-bench",
    name: "Dumbbell Bench Press",
    category: "Chest",
    muscleGroup: "Pectorals",
    secondaryMuscles: ["Triceps", "Front Delts"],
    equipment: "Dumbbells",
    caloriesPerMinute: 7,
    instructions: [
      "Sit on a flat bench with dumbbells resting on your thighs.",
      "Kick the weights up to shoulder height and lie back, palms facing forward.",
      "Press the dumbbells up until arms are straight, letting them drift slightly inward.",
      "Lower under control to a deep chest stretch with elbows at about 45°.",
    ],
  },
  {
    id: "incline-db-press",
    name: "Incline Dumbbell Press",
    category: "Chest",
    muscleGroup: "Upper Chest",
    secondaryMuscles: ["Triceps", "Front Delts"],
    equipment: "Dumbbells",
    caloriesPerMinute: 7,
    instructions: [
      "Set the bench to 30° and sit with dumbbells on your thighs.",
      "Kick the weights to shoulder height and lie back, palms facing forward.",
      "Press the dumbbells up and slightly in until they nearly touch at the top.",
      "Lower slowly to a full stretch on the upper chest.",
    ],
  },
  {
    id: "decline-db-press",
    name: "Decline Dumbbell Press",
    category: "Chest",
    muscleGroup: "Lower Chest",
    secondaryMuscles: ["Triceps", "Front Delts"],
    equipment: "Dumbbells",
    caloriesPerMinute: 7,
    instructions: [
      "Secure your legs on a decline bench with dumbbells at chest level.",
      "Keep your shoulder blades pinned and brace your core hard.",
      "Press the dumbbells up to full extension, arcing them slightly inward.",
      "Lower with control until you feel a deep stretch across your lower chest.",
    ],
  },
  {
    id: "db-flyes",
    name: "Dumbbell Flyes",
    category: "Chest",
    muscleGroup: "Pectorals",
    secondaryMuscles: ["Front Delts"],
    equipment: "Dumbbells",
    caloriesPerMinute: 5,
    instructions: [
      "Lie flat with dumbbells pressed straight up over your chest.",
      "Set a soft bend in your elbows — lock that angle, don't change it.",
      "Lower the weights in a wide arc until you feel a stretch across your chest.",
      "Squeeze your chest to bring the dumbbells back together above your chest.",
    ],
    tip: "Too much weight turns this into a sloppy press as the elbow angle collapses. If the angle opens up, drop weight and own the stretch.",
  },
  {
    id: "cable-crossover",
    name: "Cable Crossover",
    category: "Chest",
    muscleGroup: "Pectorals",
    secondaryMuscles: ["Front Delts"],
    equipment: "Cable Machine",
    caloriesPerMinute: 5.5,
    instructions: [
      "Set both pulleys high, grab a handle in each hand with palms facing down.",
      "Step forward with a slight forward lean and a soft bend at the elbows.",
      "Pull the handles down and together in front of your hips in a wide arc.",
      "Squeeze hard at the bottom, then return slowly to the stretched start.",
    ],
  },
  {
    id: "chest-press-machine",
    name: "Chest Press Machine",
    category: "Chest",
    muscleGroup: "Pectorals",
    secondaryMuscles: ["Triceps", "Front Delts"],
    equipment: "Machine",
    caloriesPerMinute: 6,
    instructions: [
      "Adjust the seat so the handles sit level with your mid-chest.",
      "Pin your back to the pad and plant your feet firmly on the floor.",
      "Press the handles forward until your arms are fully extended.",
      "Return slowly under control, stopping just before the stack touches down.",
    ],
  },
  {
    id: "pec-deck",
    name: "Pec Deck",
    category: "Chest",
    muscleGroup: "Pectorals",
    secondaryMuscles: ["Front Delts"],
    equipment: "Machine",
    caloriesPerMinute: 5,
    instructions: [
      "Sit with your back flat against the pad, feet firmly on the floor.",
      "Place your forearms on the pads with elbows at shoulder height.",
      "Squeeze the pads together in front of your chest, pausing at the peak.",
      "Open slowly to a full stretch without letting the stack touch down.",
    ],
  },
  {
    id: "machine-chest-fly",
    name: "Machine Chest Fly",
    category: "Chest",
    muscleGroup: "Chest",
    secondaryMuscles: ["Front Delts"],
    equipment: "Machine",
    caloriesPerMinute: 5.5,
    instructions: [
      "Sit with your back flat and grip the handles at chest height.",
      "Set a soft bend in your elbows and lock that angle for the whole set.",
      "Bring the handles together in front of your chest, squeezing hard at the peak.",
      "Open slowly to the starting position, controlling the stretch at the end.",
    ],
  },
  {
    id: "smith-bench-press",
    name: "Smith Machine Bench Press",
    category: "Chest",
    muscleGroup: "Chest",
    secondaryMuscles: ["Triceps", "Front Delts"],
    equipment: "Machine",
    caloriesPerMinute: 7,
    instructions: [
      "Line up a flat bench so the bar lands over your mid-chest when unracked.",
      "Grip slightly wider than shoulders and rotate the hooks off.",
      "Lower the bar to your chest with elbows tracking around 45° from your torso.",
      "Press back up to lockout without bouncing the bar off your chest.",
    ],
    tip: "The fixed bar path means any rig misalignment hits your shoulders directly. If the bar doesn't track straight down to mid-chest, reset the bench.",
  },
  {
    id: "push-ups",
    name: "Push-Ups",
    category: "Chest",
    muscleGroup: "Pectorals",
    secondaryMuscles: ["Triceps", "Front Delts", "Core"],
    equipment: "Bodyweight",
    caloriesPerMinute: 7,
    instructions: [
      "Start in a high plank, hands slightly wider than shoulders, body in a straight line.",
      "Lower your chest toward the floor, elbows tracking at about 45° from your sides.",
      "Pause just above the ground, then press back up to full extension.",
      "Keep your abs tight the whole time — no sagging hips.",
    ],
    tip: "Flared elbows (90° out) wreck your shoulders over time. If you can't hold the 45° angle, drop to knees and build up.",
  },
  {
    id: "pike-push-up",
    name: "Pike Push-Up",
    category: "Shoulders",
    muscleGroup: "Deltoids",
    secondaryMuscles: ["Triceps", "Upper Chest"],
    equipment: "Bodyweight",
    caloriesPerMinute: 6.5,
    instructions: [
      "Start in a downward-dog with hands shoulder-width and hips stacked high.",
      "Walk your feet in so your torso is nearly vertical over your hands.",
      "Bend your elbows and lower the crown of your head toward the floor.",
      "Press back up to straight arms, keeping your hips piked high throughout.",
    ],
    tip: "If your hips drift forward, it turns into a regular push-up and the shoulders stop working. Keep the pike tight or shorten the range.",
  },
  {
    id: "weighted-push-ups",
    name: "Weighted Push-Ups",
    category: "Chest",
    muscleGroup: "Chest",
    secondaryMuscles: ["Triceps", "Front Delts", "Core"],
    equipment: "Bodyweight",
    caloriesPerMinute: 8,
    instructions: [
      "Set a plate on your upper back or wear a weighted vest, then get into a high plank.",
      "Hands slightly wider than shoulders, body in a straight line from head to heels.",
      "Lower with control, elbows at 45°, until your chest is an inch off the floor.",
      "Press back up to full lockout without letting the weight shift.",
    ],
    tip: "A sliding plate wrecks the set and can hit your spine. Have a partner place it high on your shoulder blades, or switch to a vest.",
  },
  {
    id: "barbell-floor-press",
    name: "Barbell Floor Press",
    category: "Chest",
    muscleGroup: "Chest",
    secondaryMuscles: ["Triceps", "Front Delts"],
    equipment: "Barbell",
    caloriesPerMinute: 7,
    instructions: [
      "Lie on the floor under a rack, bar positioned over your mid-chest.",
      "Grip slightly wider than shoulders and plant your feet or bend your knees.",
      "Lower the bar until your upper arms touch the floor, pause for a beat.",
      "Drive the bar back up to full lockout, treating the pause as a hard reset.",
    ],
  },
  {
    id: "weighted-chest-dip",
    name: "Weighted Chest Dip",
    category: "Chest",
    muscleGroup: "Lower Chest",
    secondaryMuscles: ["Triceps", "Front Delts"],
    equipment: "Bodyweight",
    caloriesPerMinute: 8,
    instructions: [
      "Attach a dip belt or pinch a dumbbell between your feet on parallel bars.",
      "Lean your torso forward about 30° and keep a slight bend in your knees.",
      "Lower until your upper arms are parallel to the floor, chest stretched.",
      "Press back up to the top, keeping the forward lean locked throughout.",
    ],
    tip: "Going below parallel with rounded shoulders is how people tear pecs. If your shoulders feel bad mid-rep, rack the weights — don't train through it.",
  },

  // ================= BACK =================
  {
    id: "deadlift",
    name: "Deadlift",
    category: "Back",
    muscleGroup: "Full Back",
    secondaryMuscles: ["Glutes", "Hamstrings", "Core", "Traps"],
    equipment: "Barbell",
    caloriesPerMinute: 9,
    instructions: [
      "Bar over midfoot, feet hip-width, shins almost touching the bar.",
      "Hinge down, grip just outside your shins, chest up, back flat.",
      "Take a big breath, brace hard, then stand up by pushing the floor away.",
      "Lower under control — don't bounce or drop the bar.",
    ],
    tip: "If your lower back rounds on the lift, the weight's too heavy or you lost your brace. Drop a set, reset, don't train through it.",
    difficulty: "advanced",
    tempo: "1-1-2",
    commonMistakes: [
      "Rounding the lower back instead of bracing into a flat-back hinge.",
      "Starting with hips too low, turning it into a squat off the floor.",
      "Jerking the bar off the floor instead of building tension first.",
    ],
    alternatives: ["trap-bar-deadlift", "romanian-deadlift"],
    regressions: ["romanian-deadlift", "trap-bar-deadlift"],
  },
  {
    id: "barbell-row",
    name: "Barbell Row",
    category: "Back",
    muscleGroup: "Lats",
    secondaryMuscles: ["Rhomboids", "Rear Delts", "Biceps"],
    equipment: "Barbell",
    caloriesPerMinute: 7,
    instructions: [
      "Hinge at the hips with soft knees, torso around 45° to the floor.",
      "Grip the bar overhand just outside your knees, back flat.",
      "Row the bar to your lower chest by driving your elbows up and back.",
      "Lower under control to a full stretch, keeping the hinge locked.",
    ],
    tip: "If your torso keeps rising to yank the bar up, you're cheating with leg drive. Lock the hinge or drop weight — standing reps train traps, not lats.",
  },
  {
    id: "pendlay-row",
    name: "Pendlay Row",
    category: "Back",
    muscleGroup: "Lats",
    secondaryMuscles: ["Rhomboids", "Rear Delts", "Biceps", "Core"],
    equipment: "Barbell",
    caloriesPerMinute: 7.5,
    instructions: [
      "Set up with torso parallel to the floor, bar on the ground over midfoot.",
      "Grip just outside your knees, back flat, core braced hard.",
      "Explosively row the bar to your lower chest without lifting your torso.",
      "Lower it back to a dead stop on the floor and reset every rep.",
    ],
    tip: "The dead stop only works if the torso stays parallel. If your back rounds at the bottom, the weight's too heavy — this movement punishes sloppy form fast.",
  },
  {
    id: "db-row",
    name: "Dumbbell Row",
    category: "Back",
    muscleGroup: "Lats",
    secondaryMuscles: ["Rhomboids", "Rear Delts", "Biceps"],
    equipment: "Dumbbells",
    caloriesPerMinute: 6.5,
    instructions: [
      "Place one hand and the same-side knee on a bench, other foot on the floor.",
      "Hold the dumbbell with a neutral grip, letting it hang with a stretched lat.",
      "Row the dumbbell toward your hip, driving your elbow up and back.",
      "Lower under control to a full stretch before the next rep.",
    ],
  },
  {
    id: "chest-supported-db-row",
    name: "Chest-Supported Dumbbell Row",
    category: "Back",
    muscleGroup: "Mid Back",
    secondaryMuscles: ["Rhomboids", "Rear Delts", "Biceps"],
    equipment: "Dumbbells",
    caloriesPerMinute: 6.5,
    instructions: [
      "Set an incline bench to 30-45° and lie face down, dumbbells hanging below.",
      "Pin your chest to the pad so you can't use momentum.",
      "Row both dumbbells toward your hips, squeezing your shoulder blades together.",
      "Lower to a full stretch without letting your chest leave the pad.",
    ],
  },
  {
    id: "meadows-row",
    name: "Meadows Row",
    category: "Back",
    muscleGroup: "Lats",
    secondaryMuscles: ["Rhomboids", "Rear Delts", "Biceps"],
    equipment: "Barbell",
    caloriesPerMinute: 6.5,
    instructions: [
      "Anchor one end of a barbell in a landmine and stand perpendicular to it.",
      "Stagger your stance and grip the loaded end overhand.",
      "Row the end toward your hip, driving your elbow back and squeezing your lat.",
      "Lower under control to a full stretch, keeping the hinge locked.",
    ],
  },
  {
    id: "pull-ups",
    name: "Pull-Ups",
    category: "Back",
    muscleGroup: "Lats",
    secondaryMuscles: ["Biceps", "Rear Delts", "Core"],
    equipment: "Bodyweight",
    caloriesPerMinute: 8,
    instructions: [
      "Hang from the bar with an overhand grip slightly wider than shoulders.",
      "Pull your shoulder blades down and back before your arms start to move.",
      "Pull your chest toward the bar until your chin clears it.",
      "Lower under control to a full dead hang — no kipping, no swing.",
    ],
    tip: "Kipping and half-reps train nothing but your ego. If you can't hit a dead-hang chin-over-bar, use a band or lat pulldown until you can.",
  },
  {
    id: "chin-ups",
    name: "Chin-Ups",
    category: "Back",
    muscleGroup: "Lats",
    secondaryMuscles: ["Biceps", "Core"],
    equipment: "Bodyweight",
    caloriesPerMinute: 8,
    instructions: [
      "Hang from the bar with an underhand grip at shoulder-width.",
      "Pull your chest toward the bar, leading with your elbows pulling down.",
      "Clear your chin above the bar, squeezing your biceps and lats together.",
      "Lower to a full dead hang under control before the next rep.",
    ],
  },
  {
    id: "lat-pulldown",
    name: "Lat Pulldown",
    category: "Back",
    muscleGroup: "Lats",
    secondaryMuscles: ["Biceps", "Rear Delts"],
    equipment: "Cable Machine",
    caloriesPerMinute: 6,
    instructions: [
      "Sit with thighs pinned under the pad, grip the bar slightly wider than shoulders.",
      "Lean back about 20° and set your shoulder blades down and back.",
      "Pull the bar to your upper chest by driving your elbows down and back.",
      "Return slowly to a full overhead stretch, keeping tension on the lats.",
    ],
  },
  {
    id: "single-arm-lat-pulldown",
    name: "Single-Arm Lat Pulldown",
    category: "Back",
    muscleGroup: "Lats",
    secondaryMuscles: ["Biceps", "Rear Delts"],
    equipment: "Cable Machine",
    caloriesPerMinute: 6,
    instructions: [
      "Attach a single handle to a high pulley and sit or kneel facing it.",
      "Grip the handle neutrally and lean slightly away for a deeper stretch.",
      "Pull the handle down toward your side, elbow driving back behind your torso.",
      "Return slowly to a full overhead stretch and complete reps on one side.",
    ],
  },
  {
    id: "seated-row",
    name: "Seated Cable Row",
    category: "Back",
    muscleGroup: "Mid Back",
    secondaryMuscles: ["Rhomboids", "Biceps", "Rear Delts"],
    equipment: "Cable Machine",
    caloriesPerMinute: 6,
    instructions: [
      "Sit with feet braced, knees softly bent, torso upright.",
      "Grip the handle and set your shoulder blades down and back.",
      "Pull the handle to your lower ribs, elbows tracking close to your body.",
      "Extend your arms slowly without letting your lower back round.",
    ],
  },
  {
    id: "t-bar-row",
    name: "T-Bar Row",
    category: "Back",
    muscleGroup: "Mid Back",
    secondaryMuscles: ["Lats", "Rhomboids", "Biceps"],
    equipment: "Barbell",
    caloriesPerMinute: 7,
    instructions: [
      "Straddle the loaded bar or landmine and grip the handles at your shins.",
      "Hinge forward to about 45°, chest up, back flat, core braced.",
      "Row the bar toward your chest, squeezing your mid-back at the top.",
      "Lower to a full stretch without letting your back round.",
    ],
  },
  {
    id: "face-pulls",
    name: "Face Pulls",
    category: "Back",
    muscleGroup: "Rear Delts",
    secondaryMuscles: ["Rhomboids", "Traps", "Rotator Cuff"],
    equipment: "Cable Machine",
    caloriesPerMinute: 4.5,
    instructions: [
      "Set a rope at or slightly above face height and grip the ends with palms down.",
      "Step back for tension, arms extended straight toward the pulley.",
      "Pull the rope toward your face, separating the ends past your ears.",
      "Return slowly, keeping your elbows high throughout the set.",
    ],
  },
  {
    id: "rack-pull",
    name: "Rack Pull",
    category: "Back",
    muscleGroup: "Posterior Chain",
    secondaryMuscles: ["Traps", "Glutes", "Core"],
    equipment: "Barbell",
    caloriesPerMinute: 8.5,
    instructions: [
      "Set the pins so the bar sits just below your knees.",
      "Grip the bar, set your back flat, chest up, and brace hard.",
      "Stand up by driving your hips forward, finishing with shoulders stacked.",
      "Lower the bar back to the pins under control without bouncing.",
    ],
    tip: "Because the range is short, lifters stack plates and round over. If your upper back bows forward under load, cut weight — short range still hurts if form breaks.",
  },
  {
    id: "straight-arm-pulldown",
    name: "Straight-Arm Pulldown",
    category: "Back",
    muscleGroup: "Lats",
    secondaryMuscles: ["Teres Major", "Core"],
    equipment: "Cable Machine",
    caloriesPerMinute: 5.5,
    instructions: [
      "Stand facing a high pulley, grip the bar with straight arms, hinge slightly forward.",
      "Lock your elbows into a soft, fixed bend — don't change it on the set.",
      "Pull the bar down in an arc to your thighs, feeling the lats squeeze.",
      "Return slowly to a full overhead stretch without losing tension.",
    ],
  },
  {
    id: "inverted-row",
    name: "Inverted Row",
    category: "Back",
    muscleGroup: "Mid Back",
    secondaryMuscles: ["Rhomboids", "Biceps", "Core"],
    equipment: "Bodyweight",
    caloriesPerMinute: 7,
    instructions: [
      "Set a bar at waist height and hang underneath with an overhand grip.",
      "Brace your core so your body is one straight line from heels to head.",
      "Pull your chest to the bar, squeezing your shoulder blades together.",
      "Lower under control to a full arm extension without breaking the plank.",
    ],
  },

  // ================= SHOULDERS =================
  {
    id: "overhead-press",
    name: "Overhead Press",
    category: "Shoulders",
    muscleGroup: "Deltoids",
    secondaryMuscles: ["Triceps", "Upper Chest", "Core"],
    equipment: "Barbell",
    caloriesPerMinute: 7,
    instructions: [
      "Stand with feet shoulder-width, bar resting on your front delts.",
      "Grip just outside your shoulders, wrists stacked over elbows, glutes and abs braced.",
      "Press the bar straight up, tucking your chin so it clears.",
      "Punch your head through at lockout so the bar is over your ears.",
    ],
    tip: "If your lower back arches hard to get the bar up, you're losing the brace. Squeeze glutes and abs like a vice — no spinal load, no cheat press.",
  },
  {
    id: "db-shoulder-press",
    name: "Dumbbell Shoulder Press",
    category: "Shoulders",
    muscleGroup: "Deltoids",
    secondaryMuscles: ["Triceps", "Upper Chest"],
    equipment: "Dumbbells",
    caloriesPerMinute: 6.5,
    instructions: [
      "Sit on an upright bench, dumbbells at shoulder height, palms forward.",
      "Brace your abs and press your lower back into the pad.",
      "Press the dumbbells up and slightly in until they nearly touch overhead.",
      "Lower under control to shoulder height, keeping forearms vertical.",
    ],
  },
  {
    id: "lateral-raise",
    name: "Lateral Raise",
    category: "Shoulders",
    muscleGroup: "Side Delts",
    secondaryMuscles: ["Traps"],
    equipment: "Dumbbells",
    caloriesPerMinute: 4.5,
    instructions: [
      "Stand tall with dumbbells at your sides, palms facing in.",
      "Keep a slight bend in your elbows — don't lock them.",
      "Raise your arms out to the sides until they reach shoulder height.",
      "Lower slowly under control — resist the urge to drop them.",
    ],
  },
  {
    id: "reverse-pec-deck",
    name: "Reverse Pec Deck",
    category: "Shoulders",
    muscleGroup: "Rear Delts",
    secondaryMuscles: ["Traps", "Rhomboids"],
    equipment: "Machine",
    caloriesPerMinute: 4.5,
    instructions: [
      "Sit facing the pad with chest pinned, grips at shoulder height.",
      "Start with arms extended forward, soft bend in the elbows locked.",
      "Pull the handles back and out in a wide arc, squeezing your rear delts.",
      "Return slowly to a full stretch without letting the stack touch down.",
    ],
  },
  {
    id: "cable-lateral-raise",
    name: "Cable Lateral Raise",
    category: "Shoulders",
    muscleGroup: "Side Delts",
    secondaryMuscles: ["Traps"],
    equipment: "Cable Machine",
    caloriesPerMinute: 4.5,
    instructions: [
      "Stand sideways to a low pulley, grip the handle with your far hand.",
      "Keep a slight bend in your elbow and pin it to that angle.",
      "Raise your arm out to shoulder height in a smooth arc.",
      "Lower slowly with constant tension — no swinging at the bottom.",
    ],
  },
  {
    id: "front-raise",
    name: "Front Raise",
    category: "Shoulders",
    muscleGroup: "Front Delts",
    secondaryMuscles: ["Upper Chest"],
    equipment: "Dumbbells",
    caloriesPerMinute: 4.5,
    instructions: [
      "Stand with dumbbells in front of your thighs, palms facing your body.",
      "Set a slight bend in your elbows and brace your core.",
      "Raise one or both arms straight in front to shoulder height.",
      "Lower slowly under control — no swinging, no momentum.",
    ],
  },
  {
    id: "reverse-flyes",
    name: "Reverse Flyes",
    category: "Shoulders",
    muscleGroup: "Rear Delts",
    secondaryMuscles: ["Rhomboids", "Traps"],
    equipment: "Dumbbells",
    caloriesPerMinute: 4.5,
    instructions: [
      "Hinge forward at the hips with soft knees, torso near parallel to the floor.",
      "Hold dumbbells below your chest, palms facing each other, elbows soft.",
      "Raise the dumbbells out to the sides, squeezing your rear delts and upper back.",
      "Lower slowly to a full stretch without losing the hinge.",
    ],
  },
  {
    id: "rear-delt-machine-fly",
    name: "Rear Delt Machine Fly",
    category: "Shoulders",
    muscleGroup: "Rear Delts",
    secondaryMuscles: ["Rhomboids", "Traps"],
    equipment: "Machine",
    caloriesPerMinute: 4.5,
    instructions: [
      "Sit facing the pec deck pad with chest pinned, grips at shoulder height.",
      "Start with arms extended forward in a soft-bent position.",
      "Push the handles apart by squeezing your rear delts, opening wide.",
      "Return under control without letting the stack touch down.",
    ],
  },
  {
    id: "arnold-press",
    name: "Arnold Press",
    category: "Shoulders",
    muscleGroup: "Deltoids",
    secondaryMuscles: ["Triceps", "Upper Chest"],
    equipment: "Dumbbells",
    caloriesPerMinute: 6.5,
    instructions: [
      "Sit on an upright bench, dumbbells at chest height, palms facing you.",
      "As you press up, rotate the dumbbells so palms face forward at lockout.",
      "Press to full extension without letting the weights clash.",
      "Reverse the rotation on the way down to the starting position.",
    ],
  },
  {
    id: "shoulder-press-machine",
    name: "Shoulder Press Machine",
    category: "Shoulders",
    muscleGroup: "Deltoids",
    secondaryMuscles: ["Triceps"],
    equipment: "Machine",
    caloriesPerMinute: 6,
    instructions: [
      "Adjust the seat so the handles line up with shoulder height.",
      "Pin your back to the pad and grip the handles with palms forward.",
      "Press straight up to full extension without shrugging your traps.",
      "Lower under control to the starting position.",
    ],
  },
  {
    id: "smith-shoulder-press",
    name: "Smith Machine Shoulder Press",
    category: "Shoulders",
    muscleGroup: "Deltoids",
    secondaryMuscles: ["Triceps", "Upper Chest"],
    equipment: "Machine",
    caloriesPerMinute: 6.5,
    instructions: [
      "Set an upright bench under the bar so it lands at collarbone height.",
      "Sit, grip just outside your shoulders, rotate the hooks off.",
      "Press the bar straight up to lockout without flaring elbows forward.",
      "Lower under control to collarbone height, keeping forearms vertical.",
    ],
  },
  {
    id: "barbell-upright-row",
    name: "Barbell Upright Row",
    category: "Shoulders",
    muscleGroup: "Traps",
    secondaryMuscles: ["Side Delts", "Biceps"],
    equipment: "Barbell",
    caloriesPerMinute: 6,
    instructions: [
      "Stand with the bar at your thighs, overhand grip just inside shoulders.",
      "Pull the bar straight up along your body, leading with your elbows.",
      "Stop at upper chest height — elbows should not go above shoulders.",
      "Lower under control to the starting position.",
    ],
    tip: "Pulling the bar above chest height with a narrow grip impinges shoulders. If your elbows pass your shoulders, stop short or drop to a wider grip.",
  },
  {
    id: "shrugs",
    name: "Shrugs",
    category: "Shoulders",
    muscleGroup: "Traps",
    secondaryMuscles: [],
    equipment: "Dumbbells",
    caloriesPerMinute: 5,
    instructions: [
      "Stand tall with dumbbells at your sides, arms straight.",
      "Shrug your shoulders straight up toward your ears — no rolling.",
      "Squeeze your traps hard at the top for a beat.",
      "Lower slowly to a full stretch before the next rep.",
    ],
  },
  {
    id: "barbell-shrug",
    name: "Barbell Shrug",
    category: "Shoulders",
    muscleGroup: "Traps",
    secondaryMuscles: ["Forearms"],
    equipment: "Barbell",
    caloriesPerMinute: 5.5,
    instructions: [
      "Stand with the bar at your thighs, overhand grip at shoulder-width.",
      "Shrug your shoulders straight up toward your ears, arms straight.",
      "Squeeze your traps hard at the top, then lower slowly.",
      "Keep the motion strictly vertical — no rolling, no rocking.",
    ],
  },
  {
    id: "cuban-press",
    name: "Cuban Press",
    category: "Shoulders",
    muscleGroup: "Shoulders",
    secondaryMuscles: ["Rotator Cuff", "Traps"],
    equipment: "Dumbbells",
    caloriesPerMinute: 5,
    instructions: [
      "Stand with light dumbbells hanging in front of your thighs.",
      "Upright-row to chest height with elbows leading.",
      "From there, rotate your shoulders so the dumbbells point up.",
      "Press overhead, then reverse each segment back to the start.",
    ],
    tip: "This is a rotator-cuff exercise, not a strength lift. Going heavy turns it into a sloppy upright row and wrecks the shoulder joint — stay light.",
  },
  {
    id: "lu-raise",
    name: "Lu Raise",
    category: "Shoulders",
    muscleGroup: "Deltoids",
    secondaryMuscles: ["Front Delts", "Side Delts"],
    equipment: "Dumbbells",
    caloriesPerMinute: 5,
    instructions: [
      "Stand tall with light dumbbells at your sides, palms facing in.",
      "Raise your arms out to shoulder height like a lateral raise.",
      "At the top, rotate forward and bring the dumbbells together in front.",
      "Reverse through both segments back to the starting position.",
    ],
  },
  {
    id: "landmine-press",
    name: "Landmine Press",
    category: "Shoulders",
    muscleGroup: "Deltoids",
    secondaryMuscles: ["Upper Chest", "Triceps", "Core"],
    equipment: "Barbell",
    caloriesPerMinute: 6.5,
    instructions: [
      "Stagger your stance facing the landmine, bar end at shoulder height.",
      "Grip the end with one hand, other arm tucked at your side for balance.",
      "Press the bar up and forward until your arm is fully extended.",
      "Lower under control to your shoulder, keeping your ribs down.",
    ],
  },

  // ================= BICEPS =================
  {
    id: "barbell-curl",
    name: "Barbell Curl",
    category: "Biceps",
    muscleGroup: "Biceps",
    secondaryMuscles: ["Forearms"],
    equipment: "Barbell",
    caloriesPerMinute: 5,
    instructions: [
      "Stand with the bar at your thighs, underhand grip at shoulder-width.",
      "Pin your elbows to your sides — they shouldn't drift forward.",
      "Curl the bar up to shoulder height by contracting the biceps.",
      "Lower slowly to a full stretch without swinging your torso.",
    ],
    tip: "Rocking your hips back to fling the bar up is ego lifting, not biceps training. Lock the torso or drop weight — clean reps grow arms.",
  },
  {
    id: "ez-bar-curl",
    name: "EZ Bar Curl",
    category: "Biceps",
    muscleGroup: "Biceps",
    secondaryMuscles: ["Forearms"],
    equipment: "Barbell",
    caloriesPerMinute: 5,
    instructions: [
      "Stand with the EZ bar at your thighs, gripping the angled section.",
      "Keep elbows pinned at your sides and core braced.",
      "Curl the bar up to shoulder height, squeezing the biceps hard.",
      "Lower slowly to a full stretch with tension on the biceps.",
    ],
  },
  {
    id: "db-curl",
    name: "Dumbbell Curl",
    category: "Biceps",
    muscleGroup: "Biceps",
    secondaryMuscles: ["Forearms"],
    equipment: "Dumbbells",
    caloriesPerMinute: 5,
    instructions: [
      "Stand with dumbbells at your sides, palms facing forward.",
      "Pin your elbows to your ribs and set your shoulder blades back.",
      "Curl both dumbbells up to shoulder height in a smooth arc.",
      "Lower slowly with constant tension, no bouncing at the bottom.",
    ],
  },
  {
    id: "incline-db-curl",
    name: "Incline Dumbbell Curl",
    category: "Biceps",
    muscleGroup: "Biceps",
    secondaryMuscles: ["Forearms"],
    equipment: "Dumbbells",
    caloriesPerMinute: 5,
    instructions: [
      "Set a bench to 45°, sit back, arms hanging straight with palms forward.",
      "Let your shoulders open up — the stretch is the whole point.",
      "Curl the dumbbells up without letting your upper arms move forward.",
      "Lower slowly to a full biceps stretch before the next rep.",
    ],
  },
  {
    id: "hammer-curl",
    name: "Hammer Curl",
    category: "Biceps",
    muscleGroup: "Biceps",
    secondaryMuscles: ["Brachioradialis", "Forearms"],
    equipment: "Dumbbells",
    caloriesPerMinute: 5,
    instructions: [
      "Stand with dumbbells at your sides, palms facing each other.",
      "Pin your elbows at your sides — the neutral grip stays locked.",
      "Curl both dumbbells up to shoulder height, squeezing at the top.",
      "Lower slowly under control to a full stretch.",
    ],
  },
  {
    id: "cross-body-hammer-curl",
    name: "Cross-Body Hammer Curl",
    category: "Biceps",
    muscleGroup: "Biceps",
    secondaryMuscles: ["Brachioradialis", "Forearms"],
    equipment: "Dumbbells",
    caloriesPerMinute: 5,
    instructions: [
      "Stand with dumbbells at your sides, palms facing each other.",
      "Pin your elbow and curl one dumbbell across your body to the opposite shoulder.",
      "Squeeze the brachialis at the top, then lower slowly.",
      "Alternate arms and keep the torso still.",
    ],
  },
  {
    id: "zottman-curl",
    name: "Zottman Curl",
    category: "Biceps",
    muscleGroup: "Biceps",
    secondaryMuscles: ["Brachioradialis", "Forearms"],
    equipment: "Dumbbells",
    caloriesPerMinute: 5,
    instructions: [
      "Stand with dumbbells at your sides, palms facing forward.",
      "Curl up with supinated (palms up) grip to shoulder height.",
      "At the top, rotate your wrists so palms face down.",
      "Lower slowly in the pronated grip, then rotate back at the bottom.",
    ],
  },
  {
    id: "preacher-curl",
    name: "Preacher Curl",
    category: "Biceps",
    muscleGroup: "Biceps",
    secondaryMuscles: ["Forearms"],
    equipment: "Barbell",
    caloriesPerMinute: 4.5,
    instructions: [
      "Sit at the preacher bench with your upper arms flat on the pad.",
      "Grip the bar underhand at shoulder-width, armpits pressed to the pad.",
      "Curl the bar up to shoulder height without shrugging.",
      "Lower slowly to just short of full extension, keeping tension on the biceps.",
    ],
    tip: "Slamming into a fully locked-out elbow at the bottom is how biceps tendons tear. Stop just short and keep tension — control beats range here.",
  },
  {
    id: "cable-curl",
    name: "Cable Curl",
    category: "Biceps",
    muscleGroup: "Biceps",
    secondaryMuscles: ["Forearms"],
    equipment: "Cable Machine",
    caloriesPerMinute: 4.5,
    instructions: [
      "Stand facing a low cable pulley, grip the bar with an underhand grip at shoulder-width.",
      "Keep your elbows pinned to your sides — they shouldn't move.",
      "Curl the bar up toward your shoulders, squeezing at the top.",
      "Lower slowly, feeling constant tension on the way down.",
    ],
  },
  {
    id: "bayesian-cable-curl",
    name: "Bayesian Cable Curl",
    category: "Biceps",
    muscleGroup: "Biceps",
    secondaryMuscles: ["Forearms"],
    equipment: "Cable Machine",
    caloriesPerMinute: 4.5,
    instructions: [
      "Face away from a low cable, handle in one hand, stagger your stance.",
      "Let the cable pull your arm back so the elbow sits behind your torso.",
      "Curl your hand up to your shoulder, keeping the elbow behind you.",
      "Lower slowly to a full stretched biceps position.",
    ],
  },
  {
    id: "concentration-curl",
    name: "Concentration Curl",
    category: "Biceps",
    muscleGroup: "Biceps",
    secondaryMuscles: ["Forearms"],
    equipment: "Dumbbells",
    caloriesPerMinute: 4,
    instructions: [
      "Sit on a bench, spread your knees, brace your upper arm against your inner thigh.",
      "Let the dumbbell hang with a straight arm, palm facing up.",
      "Curl the dumbbell up to your shoulder, squeezing hard at the top.",
      "Lower slowly to a full stretch before the next rep.",
    ],
  },
  {
    id: "spider-db-curl",
    name: "Spider Dumbbell Curl",
    category: "Biceps",
    muscleGroup: "Biceps",
    secondaryMuscles: ["Forearms"],
    equipment: "Dumbbells",
    caloriesPerMinute: 4.5,
    instructions: [
      "Lie face down on an incline bench with arms hanging straight.",
      "Hold dumbbells with palms facing forward, chest pinned to the pad.",
      "Curl the dumbbells up to your shoulders without moving your upper arms.",
      "Lower slowly to a full stretch with constant tension.",
    ],
  },
  {
    id: "reverse-barbell-curl",
    name: "Reverse Barbell Curl",
    category: "Biceps",
    muscleGroup: "Biceps",
    secondaryMuscles: ["Brachioradialis", "Forearms"],
    equipment: "Barbell",
    caloriesPerMinute: 4.5,
    instructions: [
      "Stand with the bar at your thighs, overhand grip at shoulder-width.",
      "Pin elbows at your sides and set your wrists straight.",
      "Curl the bar up to shoulder height by squeezing the brachioradialis.",
      "Lower slowly under control, keeping the overhand grip locked.",
    ],
  },

  // ================= TRICEPS =================
  {
    id: "rope-tricep-pushdown",
    name: "Rope Tricep Pushdown",
    category: "Triceps",
    muscleGroup: "Triceps",
    secondaryMuscles: ["Forearms"],
    equipment: "Cable Machine",
    caloriesPerMinute: 5,
    instructions: [
      "Stand facing a high pulley with a rope attached, grip the ends neutrally.",
      "Pin your elbows to your ribs — that angle stays fixed all set.",
      "Push the rope down, spreading the ends apart as your arms lock out.",
      "Return slowly to a full stretch without letting elbows drift forward.",
    ],
  },
  {
    id: "skull-crushers",
    name: "Skull Crushers",
    category: "Triceps",
    muscleGroup: "Triceps",
    secondaryMuscles: ["Chest", "Front Delts"],
    equipment: "Barbell",
    caloriesPerMinute: 5.5,
    instructions: [
      "Lie flat with the bar pressed up over your chest, narrow overhand grip.",
      "Tilt your upper arms back slightly so they angle toward your head.",
      "Bend your elbows to lower the bar past your forehead toward the top of your skull.",
      "Extend back to the start by contracting the triceps, keeping upper arms still.",
    ],
    tip: "Letting elbows flare wide turns this into a sloppy close-grip press and hammers the joint. Keep elbows stacked and if they flare, drop the weight.",
  },
  {
    id: "overhead-extension",
    name: "Overhead Tricep Extension",
    category: "Triceps",
    muscleGroup: "Triceps",
    secondaryMuscles: ["Shoulders"],
    equipment: "Dumbbells",
    caloriesPerMinute: 5,
    instructions: [
      "Stand or sit, hold one dumbbell with both hands straight overhead.",
      "Keep elbows close to your ears and pointed at the ceiling.",
      "Lower the dumbbell behind your head by bending your elbows only.",
      "Extend back up to full lockout, squeezing the triceps.",
    ],
  },
  {
    id: "overhead-cable-tricep-extension",
    name: "Overhead Cable Tricep Extension",
    category: "Triceps",
    muscleGroup: "Triceps",
    secondaryMuscles: ["Shoulders"],
    equipment: "Cable Machine",
    caloriesPerMinute: 5,
    instructions: [
      "Face away from a low pulley with a rope held behind your head.",
      "Stagger your stance and lean slightly forward for stability.",
      "Extend your arms overhead until fully straight, keeping elbows close to your head.",
      "Lower slowly to a deep triceps stretch before the next rep.",
    ],
  },
  {
    id: "tricep-dips",
    name: "Tricep Dips",
    category: "Triceps",
    muscleGroup: "Triceps",
    secondaryMuscles: ["Chest", "Front Delts"],
    equipment: "Bodyweight",
    caloriesPerMinute: 7,
    instructions: [
      "Grip parallel bars with arms locked, torso upright, legs tucked or straight.",
      "Keep your chest tall — don't lean forward like a chest dip.",
      "Lower with elbows straight back until upper arms are parallel to the floor.",
      "Press up to full lockout, squeezing the triceps hard.",
    ],
    tip: "If your shoulders roll forward or hurt at the bottom, stop short of parallel or move to bench dips. Shoulder pain means the capsule is loaded, not the triceps.",
  },
  {
    id: "bench-dips",
    name: "Bench Dips",
    category: "Triceps",
    muscleGroup: "Triceps",
    secondaryMuscles: ["Chest", "Front Delts"],
    equipment: "Bodyweight",
    caloriesPerMinute: 6.5,
    instructions: [
      "Sit on a bench, hands gripping the edge, legs extended in front.",
      "Slide your hips off the bench, arms fully extended.",
      "Lower by bending your elbows to about 90°, keeping them tracking back.",
      "Press back up to full lockout without shrugging your shoulders.",
    ],
  },
  {
    id: "close-grip-bench",
    name: "Close Grip Bench Press",
    category: "Triceps",
    muscleGroup: "Triceps",
    secondaryMuscles: ["Chest", "Front Delts"],
    equipment: "Barbell",
    caloriesPerMinute: 7,
    instructions: [
      "Lie flat on a bench, grip the bar just inside shoulder-width.",
      "Unrack, pinch shoulder blades, plant your feet.",
      "Lower the bar to your lower chest with elbows tucked close to your torso.",
      "Press back to lockout, driving through the triceps.",
    ],
    tip: "Grip any closer than shoulder-width and you torque the wrists without training the triceps any harder. Shoulder-width in, elbows tucked — that's where it works.",
  },
  {
    id: "tricep-kickback",
    name: "Tricep Kickback",
    category: "Triceps",
    muscleGroup: "Triceps",
    secondaryMuscles: ["Rear Delts"],
    equipment: "Dumbbells",
    caloriesPerMinute: 4,
    instructions: [
      "Hinge forward with one knee and hand on a bench for support.",
      "Hold a dumbbell in your free hand, upper arm parallel to the floor.",
      "Extend your forearm back until the arm is fully straight, squeezing the triceps.",
      "Lower slowly to 90° at the elbow without letting the upper arm drop.",
    ],
  },
  {
    id: "single-arm-cable-pushdown",
    name: "Single-Arm Cable Pushdown",
    category: "Triceps",
    muscleGroup: "Triceps",
    secondaryMuscles: ["Forearms"],
    equipment: "Cable Machine",
    caloriesPerMinute: 4.5,
    instructions: [
      "Attach a single handle to a high pulley, grip neutrally with one hand.",
      "Pin your elbow at your side — it stays put the whole set.",
      "Push the handle down by extending your elbow to full lockout.",
      "Return slowly to a full stretch and complete reps on one side.",
    ],
  },
  {
    id: "reverse-grip-cable-pushdown",
    name: "Reverse Grip Cable Pushdown",
    category: "Triceps",
    muscleGroup: "Triceps",
    secondaryMuscles: ["Forearms"],
    equipment: "Cable Machine",
    caloriesPerMinute: 4.5,
    instructions: [
      "Attach a straight bar to a high pulley, grip underhand at shoulder-width.",
      "Pin your elbows to your sides and set your wrists straight.",
      "Push the bar down by extending your elbows to full lockout.",
      "Return slowly with constant tension, keeping elbows fixed.",
    ],
  },
  {
    id: "jm-press",
    name: "JM Press",
    category: "Triceps",
    muscleGroup: "Triceps",
    secondaryMuscles: ["Chest", "Front Delts"],
    equipment: "Barbell",
    caloriesPerMinute: 6,
    instructions: [
      "Lie flat, bar pressed up over your chest with a shoulder-width grip.",
      "Lower the bar toward your upper chin by bending the elbows forward.",
      "Let the bar sink close to your throat but never touch down.",
      "Press back to lockout by driving the elbows forward and up.",
    ],
    tip: "This is halfway between a skull crusher and a close-grip bench — go light until the groove is dialled in. Elbow strain here sidelines pressing for weeks.",
  },
  {
    id: "diamond-push-ups",
    name: "Diamond Push-Ups",
    category: "Triceps",
    muscleGroup: "Triceps",
    secondaryMuscles: ["Chest", "Front Delts"],
    equipment: "Bodyweight",
    caloriesPerMinute: 7,
    instructions: [
      "Start in a high plank with hands close together forming a diamond under your chest.",
      "Brace your core so your body is one straight line.",
      "Lower your chest to your hands, elbows tracking back along your ribs.",
      "Press back up to full extension without sagging hips.",
    ],
  },

  // ================= LEGS =================
  {
    id: "squat",
    name: "Barbell Squat",
    category: "Legs",
    muscleGroup: "Quads",
    secondaryMuscles: ["Glutes", "Hamstrings", "Core"],
    equipment: "Barbell",
    caloriesPerMinute: 9,
    instructions: [
      "Bar on your upper traps, feet shoulder-width, toes slightly out.",
      "Brace your abs like you're about to get punched, then unrack.",
      "Push hips back and bend knees together, lower until thighs are at or below parallel.",
      "Drive through your whole foot to stand, squeezing glutes at the top.",
    ],
    tip: "If your knees cave inward on the way up, think push the floor apart with your feet. This is the #1 form error and it costs you power.",
    difficulty: "intermediate",
    tempo: "2-1-1",
    commonMistakes: [
      "Knees caving inward (valgus) on the drive out of the hole.",
      "Heels lifting / weight shifting onto the toes.",
      "Cutting depth short of parallel under heavier loads.",
    ],
    alternatives: ["front-squat", "hack-squat", "leg-press"],
    regressions: ["leg-press", "bulgarian-split"],
    media: [
      "exercise-demos/squat/start.png",
      "exercise-demos/squat/finish.png",
    ],
  },
  {
    id: "front-squat",
    name: "Front Squat",
    category: "Legs",
    muscleGroup: "Quads",
    secondaryMuscles: ["Glutes", "Core"],
    equipment: "Barbell",
    caloriesPerMinute: 9,
    instructions: [
      "Rack the bar on your front delts with elbows pointing forward and high.",
      "Feet shoulder-width, toes slightly out, core braced hard.",
      "Squat down with an upright torso until thighs are at or below parallel.",
      "Drive up through your whole foot, keeping elbows high all the way.",
    ],
    tip: "If your elbows drop, the bar rolls off your shoulders and onto your neck. Keep elbows up like you're holding a tray — dropped elbows end the set.",
  },
  {
    id: "goblet-squat",
    name: "Goblet Squat",
    category: "Legs",
    muscleGroup: "Quads",
    secondaryMuscles: ["Glutes", "Core"],
    equipment: "Dumbbells",
    caloriesPerMinute: 7,
    instructions: [
      "Hold a dumbbell vertically against your chest, elbows pinned under it.",
      "Feet shoulder-width, toes slightly out, core braced.",
      "Squat down between your legs, elbows tracking inside your knees.",
      "Drive up through your heels, keeping the dumbbell glued to your chest.",
    ],
  },
  {
    id: "sissy-squat",
    name: "Sissy Squat",
    category: "Legs",
    muscleGroup: "Quads",
    secondaryMuscles: ["Hip Flexors"],
    equipment: "Bodyweight",
    caloriesPerMinute: 6,
    instructions: [
      "Stand with feet shoulder-width, grip something solid for balance.",
      "Rise onto your toes and lean your torso back as you bend the knees forward.",
      "Lower until you feel a deep stretch across the quads and hip flexors.",
      "Squeeze your quads to drive back to standing.",
    ],
    tip: "This loads the knees heavily — skip it if you've got patellar issues, and stay bodyweight until quads can handle the range. Don't add load until form is locked.",
  },
  {
    id: "smith-machine-squat",
    name: "Smith Machine Squat",
    category: "Legs",
    muscleGroup: "Quads",
    secondaryMuscles: ["Glutes", "Hamstrings"],
    equipment: "Machine",
    caloriesPerMinute: 8,
    instructions: [
      "Position yourself under the bar with it racked on your upper traps.",
      "Feet slightly in front of your hips to accommodate the fixed path.",
      "Rotate the hooks off and squat down until thighs are parallel.",
      "Drive up through the whole foot back to the start.",
    ],
  },
  {
    id: "hack-squat",
    name: "Hack Squat",
    category: "Legs",
    muscleGroup: "Quads",
    secondaryMuscles: ["Glutes"],
    equipment: "Machine",
    caloriesPerMinute: 8,
    instructions: [
      "Set your back flat against the pad, shoulders under the pads, feet mid-platform.",
      "Rotate the hooks off and brace your core.",
      "Lower until your thighs are parallel to the platform, knees tracking over toes.",
      "Press back up through your heels without locking out hard.",
    ],
  },
  {
    id: "leg-press",
    name: "Leg Press",
    category: "Legs",
    muscleGroup: "Quads",
    secondaryMuscles: ["Glutes", "Hamstrings"],
    equipment: "Machine",
    caloriesPerMinute: 7.5,
    instructions: [
      "Sit with your back flat against the pad, feet shoulder-width mid-platform.",
      "Release the safety bars and lower the platform toward your chest.",
      "Stop when your thighs are near your ribs or your lower back starts to round.",
      "Press back up without fully locking the knees.",
    ],
    tip: "Loading deep until your lower back rounds off the pad is how people herniate discs on the leg press. Stop the range where the back stays glued to the pad.",
  },
  {
    id: "leg-extension",
    name: "Leg Extension",
    category: "Legs",
    muscleGroup: "Quads",
    secondaryMuscles: ["Hip Flexors"],
    equipment: "Machine",
    caloriesPerMinute: 5,
    instructions: [
      "Sit in the machine, adjust the pad so it sits on your shins, just above the ankle.",
      "Grip the side handles and keep your hips pressed into the seat.",
      "Extend your legs smoothly until they're fully straight, squeeze the quads at the top.",
      "Lower with control — don't let the stack crash.",
    ],
  },
  {
    id: "seated-leg-curl",
    name: "Seated Leg Curl",
    category: "Legs",
    muscleGroup: "Hamstrings",
    secondaryMuscles: ["Calves"],
    equipment: "Machine",
    caloriesPerMinute: 5,
    instructions: [
      "Sit with the thigh pad pinning your legs and the ankle pad on your lower calves.",
      "Grip the handles and pin your hips to the seat.",
      "Curl your legs down and back by driving the heels toward the floor.",
      "Return slowly to the start without letting the stack touch down.",
    ],
  },
  {
    id: "romanian-deadlift",
    name: "Romanian Deadlift",
    category: "Legs",
    muscleGroup: "Hamstrings",
    secondaryMuscles: ["Glutes", "Lower Back"],
    equipment: "Barbell",
    caloriesPerMinute: 8,
    instructions: [
      "Start standing, bar at your hips, feet hip-width, soft knees locked.",
      "Push your hips back and slide the bar down your thighs, back flat.",
      "Lower until you feel a strong hamstring stretch — usually mid-shin.",
      "Drive your hips forward to stand, squeezing glutes at lockout.",
    ],
    tip: "If you turn this into a squat by bending the knees, you've lost the movement. Knees stay soft but fixed — the hips do the work.",
  },
  {
    id: "db-rdl",
    name: "Dumbbell Romanian Deadlift",
    category: "Legs",
    muscleGroup: "Hamstrings",
    secondaryMuscles: ["Glutes", "Lower Back"],
    equipment: "Dumbbells",
    caloriesPerMinute: 7,
    instructions: [
      "Stand with dumbbells at your thighs, feet hip-width, soft knees.",
      "Hinge at the hips and slide the dumbbells down your legs, back flat.",
      "Lower until you feel a strong hamstring stretch, usually mid-shin.",
      "Drive your hips forward to stand, squeezing glutes at lockout.",
    ],
  },
  {
    id: "nordic-hamstring-curl",
    name: "Nordic Hamstring Curl",
    category: "Legs",
    muscleGroup: "Hamstrings",
    secondaryMuscles: ["Calves"],
    equipment: "Bodyweight",
    caloriesPerMinute: 7,
    instructions: [
      "Kneel on a pad with a partner or strap anchoring your ankles firmly.",
      "Cross arms over your chest and keep your body dead straight.",
      "Lower slowly forward by extending at the knees, fighting gravity.",
      "Pull yourself back up with the hamstrings, or push off the floor.",
    ],
    tip: "This is one of the hardest lifts in the gym. Start with a band for assistance or just the eccentric — ego reps here snap hamstrings.",
  },
  {
    id: "glute-ham-raise",
    name: "Glute-Ham Raise",
    category: "Legs",
    muscleGroup: "Hamstrings",
    secondaryMuscles: ["Glutes", "Calves"],
    equipment: "Machine",
    caloriesPerMinute: 7,
    instructions: [
      "Set the GHD so your thighs press into the pad and feet are secured.",
      "Start upright, core braced, hands crossed over your chest.",
      "Lower your torso by extending at the knees with a straight line from knees to head.",
      "Curl yourself back up using your hamstrings and glutes.",
    ],
  },
  {
    id: "sumo-deadlift",
    name: "Sumo Deadlift",
    category: "Legs",
    muscleGroup: "Glutes",
    secondaryMuscles: ["Quads", "Hamstrings", "Adductors", "Core"],
    equipment: "Barbell",
    caloriesPerMinute: 9,
    instructions: [
      "Take a very wide stance, toes pointed out, shins at the bar.",
      "Grip the bar between your legs with straight arms, hips low.",
      "Brace hard, pull slack out of the bar, then stand up by driving the floor apart.",
      "Lower under control, knees tracking over your toes all the way down.",
    ],
    tip: "If your hips shoot up first, you're a stiff-leg deadlift with wide feet. Drive knees and hips up together — wide stance means legs stay involved.",
  },
  {
    id: "trap-bar-deadlift",
    name: "Trap Bar Deadlift",
    category: "Legs",
    muscleGroup: "Glutes",
    secondaryMuscles: ["Quads", "Hamstrings", "Core", "Traps"],
    equipment: "Barbell",
    caloriesPerMinute: 9,
    instructions: [
      "Stand inside the trap bar, feet hip-width, grip both handles.",
      "Drop your hips, chest up, back flat, arms straight.",
      "Stand up by pushing the floor away, finishing with shoulders stacked.",
      "Lower under control, hips back first, then knees bend.",
    ],
  },
  {
    id: "lunges",
    name: "Lunges",
    category: "Legs",
    muscleGroup: "Quads",
    secondaryMuscles: ["Glutes", "Hamstrings"],
    equipment: "Dumbbells",
    caloriesPerMinute: 7,
    instructions: [
      "Stand with dumbbells at your sides, core braced, eyes forward.",
      "Step forward into a long stride, both knees bending to about 90°.",
      "Lower your back knee toward the floor without crashing into it.",
      "Drive through your front heel to return to standing and alternate.",
    ],
  },
  {
    id: "bodyweight-lunge",
    name: "Bodyweight Lunge",
    category: "Legs",
    muscleGroup: "Quads",
    secondaryMuscles: ["Glutes", "Hamstrings"],
    equipment: "Bodyweight",
    caloriesPerMinute: 6,
    instructions: [
      "Stand tall with hands on your hips, core braced.",
      "Step forward into a long stride, both knees bending to about 90°.",
      "Lower your back knee toward the floor with control.",
      "Drive through your front heel to return to standing and alternate.",
    ],
  },
  {
    id: "bodyweight-squat",
    name: "Bodyweight Squat",
    category: "Legs",
    muscleGroup: "Quads",
    secondaryMuscles: ["Glutes", "Core"],
    equipment: "Bodyweight",
    caloriesPerMinute: 5.5,
    instructions: [
      "Stand with feet shoulder-width, toes slightly out, arms out for balance.",
      "Push your hips back and bend your knees together to squat down.",
      "Lower until thighs are at or below parallel, torso leaning forward naturally.",
      "Drive through the whole foot to stand, squeezing glutes at the top.",
    ],
  },
  {
    id: "walking-dumbbell-lunges",
    name: "Walking Dumbbell Lunges",
    category: "Legs",
    muscleGroup: "Quads",
    secondaryMuscles: ["Glutes", "Hamstrings"],
    equipment: "Dumbbells",
    caloriesPerMinute: 7.5,
    instructions: [
      "Stand with dumbbells at your sides, chest up, core braced.",
      "Step forward into a long lunge, back knee hovering off the floor.",
      "Drive off your front foot and step straight into the next lunge.",
      "Keep walking forward in a straight line, alternating legs.",
    ],
  },
  {
    id: "bulgarian-split",
    name: "Bulgarian Split Squat",
    category: "Legs",
    muscleGroup: "Quads",
    secondaryMuscles: ["Glutes", "Hamstrings"],
    equipment: "Dumbbells",
    caloriesPerMinute: 7.5,
    instructions: [
      "Stand about two feet in front of a bench, back foot laces-down on the bench.",
      "Hold dumbbells at your sides, torso upright, core braced.",
      "Lower your back knee toward the floor by bending the front knee.",
      "Drive through the front heel to stand, completing reps before switching.",
    ],
    tip: "If your front knee caves inward under load, drop weight. This is a one-leg loaded movement — caving knees mean the hip can't handle the stress yet.",
  },
  {
    id: "barbell-step-ups",
    name: "Barbell Step-Ups",
    category: "Legs",
    muscleGroup: "Quads",
    secondaryMuscles: ["Glutes", "Hamstrings"],
    equipment: "Barbell",
    caloriesPerMinute: 7.5,
    instructions: [
      "Position a sturdy box at knee height, bar racked on your upper traps.",
      "Step one foot fully onto the box, drive through that heel to stand up.",
      "Bring the trailing leg up, then step back down under control.",
      "Alternate legs or finish all reps before switching.",
    ],
  },
  {
    id: "calf-raise",
    name: "Calf Raise",
    category: "Legs",
    muscleGroup: "Calves",
    secondaryMuscles: ["Soleus"],
    equipment: "Machine",
    caloriesPerMinute: 4,
    instructions: [
      "Set the pads on your shoulders, balls of your feet on the platform edge.",
      "Rise up onto your toes as high as possible, squeezing the calves hard.",
      "Pause briefly at the top contraction.",
      "Lower slowly to a full stretch below the platform.",
    ],
  },
  {
    id: "standing-calf-raise",
    name: "Standing Calf Raise",
    category: "Legs",
    muscleGroup: "Calves",
    secondaryMuscles: ["Soleus"],
    equipment: "Machine",
    caloriesPerMinute: 4,
    instructions: [
      "Stand tall with the pads on your shoulders, balls of your feet on the edge.",
      "Keep your legs straight — that's what targets the gastrocnemius.",
      "Rise onto your toes as high as possible, pausing at the peak.",
      "Lower slowly to a deep stretch below the platform.",
    ],
  },
  {
    id: "seated-calf-raise",
    name: "Seated Calf Raise",
    category: "Legs",
    muscleGroup: "Calves",
    secondaryMuscles: [],
    equipment: "Machine",
    caloriesPerMinute: 3.5,
    instructions: [
      "Sit with the pads on your lower thighs, balls of your feet on the platform.",
      "Release the safety lever and drop your heels below the platform for a stretch.",
      "Raise your heels as high as possible, squeezing the soleus at the top.",
      "Lower slowly to a full stretch for the next rep.",
    ],
  },
  {
    id: "donkey-calf-raise",
    name: "Donkey Calf Raise",
    category: "Legs",
    muscleGroup: "Calves",
    secondaryMuscles: ["Soleus"],
    equipment: "Machine",
    caloriesPerMinute: 4.5,
    instructions: [
      "Set the pad on your lower back and hinge forward to about 90°.",
      "Place the balls of your feet on the platform, heels hanging.",
      "Rise up onto your toes, squeezing calves hard at the top.",
      "Lower slowly to a deep stretch below the platform.",
    ],
  },
  {
    id: "hip-thrust",
    name: "Hip Thrust",
    category: "Legs",
    muscleGroup: "Glutes",
    secondaryMuscles: ["Hamstrings", "Core"],
    equipment: "Barbell",
    caloriesPerMinute: 7,
    instructions: [
      "Sit on the floor with your upper back against a padded bench.",
      "Roll a loaded bar over your hips, feet flat, knees bent at about 90°.",
      "Drive through your heels to lift your hips, forming a straight line from shoulders to knees.",
      "Lower under control, keeping your ribs stacked over your pelvis.",
    ],
    tip: "Hyperextending at the top — ribs flaring up — loads your lower back, not your glutes. Squeeze glutes hard, keep ribs down, stop when hips are in line.",
  },
  {
    id: "glute-bridge",
    name: "Glute Bridge",
    category: "Legs",
    muscleGroup: "Glutes",
    secondaryMuscles: ["Hamstrings", "Core"],
    equipment: "Bodyweight",
    caloriesPerMinute: 4.5,
    instructions: [
      "Lie on your back, knees bent, feet flat, arms by your sides.",
      "Drive through your heels to lift your hips toward the ceiling.",
      "Squeeze glutes hard at the top, hips stacked in line with knees and shoulders.",
      "Lower under control to the floor for the next rep.",
    ],
  },
  {
    id: "hip-abduction-machine",
    name: "Hip Abduction Machine",
    category: "Legs",
    muscleGroup: "Glutes",
    secondaryMuscles: ["Hip Flexors"],
    equipment: "Machine",
    caloriesPerMinute: 4.5,
    instructions: [
      "Sit with your back pinned to the pad, pads on the outside of your knees.",
      "Grip the handles and brace your core.",
      "Push your legs apart as wide as the machine allows, squeezing outer glutes.",
      "Return slowly to the start without letting the stack touch down.",
    ],
  },
  {
    id: "hip-adduction-machine",
    name: "Hip Adduction Machine",
    category: "Legs",
    muscleGroup: "Adductors",
    secondaryMuscles: ["Glutes"],
    equipment: "Machine",
    caloriesPerMinute: 4.5,
    instructions: [
      "Sit with your back pinned to the pad, pads on the inside of your knees.",
      "Grip the handles and brace your core.",
      "Squeeze your legs together, contracting the inner thighs hard.",
      "Return slowly to a full stretch without letting the stack touch.",
    ],
  },
  {
    id: "cable-glute-kickback",
    name: "Cable Glute Kickback",
    category: "Legs",
    muscleGroup: "Glutes",
    secondaryMuscles: ["Hamstrings"],
    equipment: "Cable Machine",
    caloriesPerMinute: 4.5,
    instructions: [
      "Attach an ankle strap to a low pulley and face the stack.",
      "Grip the frame for balance, hinge slightly, core braced.",
      "Kick the working leg straight back, squeezing the glute at full extension.",
      "Return slowly without letting the stack touch down.",
    ],
  },
  {
    id: "pistol-squat",
    name: "Pistol Squats",
    category: "Legs",
    muscleGroup: "Quads",
    secondaryMuscles: ["Glutes", "Hamstrings", "Core"],
    equipment: "Bodyweight",
    caloriesPerMinute: 8,
    instructions: [
      "Stand on one leg, other leg extended straight in front, arms forward for balance.",
      "Sit back and down on the working leg, keeping the other leg off the ground.",
      "Lower until your butt nearly touches the heel of your working foot.",
      "Drive through the heel to stand back up, finishing before switching legs.",
    ],
    tip: "If the standing knee caves or the heel lifts, you don't have the strength yet. Use a TRX strap or pistol-squat to a box until you can control the full range.",
  },

  // ================= CORE =================
  {
    id: "plank",
    name: "Plank",
    category: "Core",
    muscleGroup: "Core",
    secondaryMuscles: ["Shoulders", "Glutes"],
    equipment: "Bodyweight",
    caloriesPerMinute: 4,
    instructions: [
      "Get on your forearms, elbows directly under your shoulders.",
      "Extend your legs back, tuck your toes under, and lift your hips off the floor.",
      "Make one straight line from the back of your head to your heels.",
      "Squeeze glutes and abs, breathe normally, hold for time.",
    ],
  },
  {
    id: "superman-hold",
    name: "Superman Hold",
    category: "Core",
    muscleGroup: "Lower Back",
    secondaryMuscles: ["Glutes", "Hamstrings"],
    equipment: "Bodyweight",
    caloriesPerMinute: 3.5,
    instructions: [
      "Lie face-down with arms extended overhead and legs straight.",
      "Engage your glutes and lower back to lift arms, chest, and legs off the floor.",
      "Hold the top briefly, reaching long through fingers and toes.",
      "Lower under control to the floor for the next rep.",
    ],
  },
  {
    id: "side-plank",
    name: "Side Plank",
    category: "Core",
    muscleGroup: "Obliques",
    secondaryMuscles: ["Core", "Shoulders"],
    equipment: "Bodyweight",
    caloriesPerMinute: 4,
    instructions: [
      "Lie on your side with your forearm on the floor, elbow under your shoulder.",
      "Stack your feet (or stagger for easier) and brace your core.",
      "Lift your hips off the floor into a straight line from head to feet.",
      "Hold for time, breathing normally, then switch sides.",
    ],
  },
  {
    id: "weighted-plank",
    name: "Weighted Plank",
    category: "Core",
    muscleGroup: "Core",
    secondaryMuscles: ["Shoulders", "Glutes"],
    equipment: "Bodyweight",
    caloriesPerMinute: 5,
    instructions: [
      "Get into a forearm plank, elbows under shoulders, body straight.",
      "Have a partner place a plate on your upper back over the shoulder blades.",
      "Brace harder — abs, glutes, lats all firing.",
      "Hold rigid for time, breathing shallowly through the brace.",
    ],
    tip: "A sliding plate drags down your spine and can hit your head. Use a partner who can pin it on shoulder blades, or skip to a weighted vest.",
  },
  {
    id: "crunches",
    name: "Crunches",
    category: "Core",
    muscleGroup: "Abs",
    secondaryMuscles: ["Hip Flexors"],
    equipment: "Bodyweight",
    caloriesPerMinute: 5,
    instructions: [
      "Lie on your back, knees bent, feet flat, hands lightly behind your head.",
      "Curl your shoulders off the floor by contracting your abs.",
      "Don't pull on your neck — let the abs do the work.",
      "Lower slowly to the floor with control.",
    ],
  },
  {
    id: "bicycle-crunch",
    name: "Bicycle Crunch",
    category: "Core",
    muscleGroup: "Obliques",
    secondaryMuscles: ["Abs"],
    equipment: "Bodyweight",
    caloriesPerMinute: 5.5,
    instructions: [
      "Lie on your back, hands behind your head, legs lifted at 90°.",
      "Bring one knee toward your chest while rotating the opposite elbow to meet it.",
      "Extend the opposite leg straight out without letting it touch down.",
      "Alternate sides in a smooth, controlled pedal.",
    ],
  },
  {
    id: "decline-sit-up",
    name: "Decline Sit-Up",
    category: "Core",
    muscleGroup: "Abs",
    secondaryMuscles: ["Hip Flexors"],
    equipment: "Bodyweight",
    caloriesPerMinute: 5.5,
    instructions: [
      "Secure your feet at the top of a decline bench and lie back.",
      "Cross arms over your chest or hold a plate for resistance.",
      "Sit up by curling your torso, bringing your chest toward your knees.",
      "Lower with control to a full extension without slamming.",
    ],
  },
  {
    id: "leg-raise",
    name: "Hanging Leg Raise",
    category: "Core",
    muscleGroup: "Lower Abs",
    secondaryMuscles: ["Hip Flexors", "Core"],
    equipment: "Bodyweight",
    caloriesPerMinute: 6,
    instructions: [
      "Hang from a pull-up bar with straight arms, shoulders packed down.",
      "Brace your core to eliminate any swing.",
      "Raise your legs straight in front until they're parallel to the floor or higher.",
      "Lower slowly under control — no kicking back to reset.",
    ],
    tip: "If you can't raise legs without swinging, you're using momentum not abs. Bend knees for an easier version or lower reps per set.",
  },
  {
    id: "toe-touches",
    name: "Toe Touches",
    category: "Core",
    muscleGroup: "Abs",
    secondaryMuscles: ["Hip Flexors"],
    equipment: "Bodyweight",
    caloriesPerMinute: 5,
    instructions: [
      "Lie on your back with legs extended straight up toward the ceiling.",
      "Reach your hands up toward your toes, curling your shoulders off the floor.",
      "Pause briefly at the top contraction.",
      "Lower under control to the floor for the next rep.",
    ],
  },
  {
    id: "russian-twist",
    name: "Russian Twist",
    category: "Core",
    muscleGroup: "Obliques",
    secondaryMuscles: ["Abs", "Hip Flexors"],
    equipment: "Bodyweight",
    caloriesPerMinute: 5.5,
    instructions: [
      "Sit on the floor, knees bent, lean back to about 45° with a flat back.",
      "Hold a plate or clasp your hands together in front of your chest.",
      "Rotate your torso side to side, tapping the weight just outside your hips.",
      "Keep your chest tall — no rounding the back to cheat the range.",
    ],
  },
  {
    id: "mountain-climbers",
    name: "Mountain Climbers",
    category: "Core",
    muscleGroup: "Core",
    secondaryMuscles: ["Shoulders", "Hip Flexors", "Quads"],
    equipment: "Bodyweight",
    caloriesPerMinute: 8,
    instructions: [
      "Start in a high plank, hands under shoulders, body straight.",
      "Drive one knee toward your chest without letting hips pike up.",
      "Quickly switch legs, alternating in a smooth running rhythm.",
      "Keep the plank tight — hips level, core braced, no bouncing.",
    ],
  },
  {
    id: "cable-crunch",
    name: "Cable Crunch",
    category: "Core",
    muscleGroup: "Abs",
    secondaryMuscles: ["Obliques"],
    equipment: "Cable Machine",
    caloriesPerMinute: 5,
    instructions: [
      "Kneel facing a high pulley with a rope attachment held at your temples.",
      "Set your hips back slightly so tension stays on the abs.",
      "Crunch your torso down toward your thighs, elbows driving to knees.",
      "Return slowly to upright, keeping hips fixed — this is an ab crunch, not a hip pull.",
    ],
  },
  {
    id: "cable-woodchopper",
    name: "Cable Woodchopper",
    category: "Core",
    muscleGroup: "Obliques",
    secondaryMuscles: ["Core", "Shoulders"],
    equipment: "Cable Machine",
    caloriesPerMinute: 5,
    instructions: [
      "Set the cable to the highest position, grip the handle with both hands.",
      "Stand sideways to the pulley, feet shoulder-width, soft knees.",
      "Pull the handle diagonally across your body from high to low, rotating your torso.",
      "Return slowly to the start and complete reps before switching sides.",
    ],
  },
  {
    id: "pallof-press",
    name: "Pallof Press",
    category: "Core",
    muscleGroup: "Core",
    secondaryMuscles: ["Obliques"],
    equipment: "Cable Machine",
    caloriesPerMinute: 4.5,
    instructions: [
      "Stand sideways to the cable at chest height, grip the handle with both hands.",
      "Step out for tension, feet shoulder-width, core braced hard.",
      "Press the handle straight out in front of your chest, resisting the rotation.",
      "Return slowly to your chest without letting the cable twist you.",
    ],
  },
  {
    id: "dead-bug",
    name: "Dead Bug",
    category: "Core",
    muscleGroup: "Core",
    secondaryMuscles: ["Hip Flexors"],
    equipment: "Bodyweight",
    caloriesPerMinute: 4,
    instructions: [
      "Lie on your back, arms straight up toward the ceiling, knees bent at 90°.",
      "Press your lower back into the floor — that contact stays all set.",
      "Slowly extend one arm overhead and straighten the opposite leg.",
      "Return to start and alternate sides, keeping the back pinned.",
    ],
  },
  {
    id: "dragon-flag",
    name: "Dragon Flag",
    category: "Core",
    muscleGroup: "Core",
    secondaryMuscles: ["Hip Flexors", "Lower Back"],
    equipment: "Bodyweight",
    caloriesPerMinute: 7,
    instructions: [
      "Lie on a bench, gripping the edge behind your head firmly.",
      "Raise your whole body vertically, supported only on your upper back.",
      "Lower as one rigid plank until nearly parallel to the bench.",
      "Press back up with control, never letting the hips bend.",
    ],
    tip: "This is an advanced move — start with tuck or one-leg variants. A broken plank mid-rep loads the lumbar spine hard.",
  },
  {
    id: "ab-wheel",
    name: "Ab Wheel Rollout",
    category: "Core",
    muscleGroup: "Core",
    secondaryMuscles: ["Lats", "Shoulders"],
    equipment: "Ab Wheel",
    caloriesPerMinute: 6,
    instructions: [
      "Kneel on a pad holding the ab wheel with both hands under your shoulders.",
      "Brace your core and tuck your pelvis so your back is neutral.",
      "Roll the wheel forward as far as you can control, body staying straight.",
      "Pull the wheel back toward your knees using your abs, not your hips.",
    ],
    tip: "If your lower back arches or you collapse at the bottom, you're past your controlled range. Shorten the rollout until the brace holds, then extend over time.",
  },
  {
    id: "l-sit",
    name: "L-Sit",
    category: "Core",
    muscleGroup: "Core",
    secondaryMuscles: ["Hip Flexors", "Triceps", "Shoulders"],
    equipment: "Bodyweight",
    caloriesPerMinute: 5.5,
    instructions: [
      "Support yourself on parallel bars or the floor with straight arms, shoulders packed.",
      "Raise your legs straight out in front of you until they're parallel to the ground.",
      "Point your toes and hold the L-shape with your core engaged.",
      "Hold for time, breathing shallowly, then lower under control.",
    ],
  },

  // ================= FULL BODY =================
  {
    id: "clean-and-press",
    name: "Clean and Press",
    category: "Full Body",
    muscleGroup: "Full Body",
    secondaryMuscles: ["Shoulders", "Legs", "Core"],
    equipment: "Barbell",
    caloriesPerMinute: 10,
    instructions: [
      "Set up over the bar like a deadlift, feet hip-width, back flat.",
      "Explosively extend hips and catch the bar on your front delts.",
      "Dip into a quarter squat and drive the bar overhead to lockout.",
      "Lower to shoulders, then to the floor with control before the next rep.",
    ],
    tip: "This is a technical Olympic-style lift — go light until the catch is clean. A soft back or a bar that lands on your collarbones means the pull needs more work first.",
  },
  {
    id: "kettlebell-swing",
    name: "Kettlebell Swing",
    category: "Full Body",
    muscleGroup: "Full Body",
    secondaryMuscles: ["Glutes", "Hamstrings", "Core"],
    equipment: "Kettlebell",
    caloriesPerMinute: 10,
    instructions: [
      "Stand with feet shoulder-width, bell on the floor a foot in front of you.",
      "Hinge at the hips and grip the handle with both hands, back flat.",
      "Hike the bell back between your legs, then snap your hips forward.",
      "Let the bell float to chest height without lifting with your arms.",
    ],
    tip: "This is a hip hinge, not a squat or a front raise. If you're lifting with your shoulders or bending knees deep, reset — the hips launch the bell.",
  },
  {
    id: "burpees",
    name: "Burpees",
    category: "Full Body",
    muscleGroup: "Full Body",
    secondaryMuscles: ["Chest", "Legs", "Core"],
    equipment: "Bodyweight",
    caloriesPerMinute: 10,
    instructions: [
      "Drop into a squat with your hands on the floor in front of you.",
      "Kick your feet back into a plank, lower your chest to the floor.",
      "Press back up, jump your feet forward to your hands.",
      "Explode upward into a jump with arms overhead, then repeat.",
    ],
  },
  {
    id: "thrusters",
    name: "Thrusters",
    category: "Full Body",
    muscleGroup: "Full Body",
    secondaryMuscles: ["Quads", "Shoulders", "Core"],
    equipment: "Barbell",
    caloriesPerMinute: 9.5,
    instructions: [
      "Hold the bar in a front rack, elbows high, feet shoulder-width.",
      "Squat down with an upright torso until thighs are parallel.",
      "Drive up explosively and use the leg momentum to press the bar overhead.",
      "Lower the bar back to the rack and squat again in one fluid cycle.",
    ],
  },
  {
    id: "farmers-carry",
    name: "Farmer's Carry",
    category: "Full Body",
    muscleGroup: "Full Body",
    secondaryMuscles: ["Forearms", "Traps", "Core"],
    equipment: "Dumbbells",
    caloriesPerMinute: 9,
    instructions: [
      "Pick up heavy dumbbells or kettlebells with a deadlift setup.",
      "Stand tall with shoulders packed down and back, core braced.",
      "Walk forward in short controlled steps, eyes up, chest proud.",
      "Set the weights down with control — no dropping at the finish.",
    ],
  },
  {
    id: "sled-push-pull",
    name: "Sled Push/Pull",
    category: "Full Body",
    muscleGroup: "Full Body",
    secondaryMuscles: ["Quads", "Glutes", "Core"],
    equipment: "Machine",
    caloriesPerMinute: 10,
    instructions: [
      "For the push: grip the handles low, lean in, drive through your feet in short powerful strides.",
      "For the pull: attach a rope, face the sled, hinge and pull it toward you hand over hand.",
      "Keep your core braced and breathing steady — no holding your breath.",
      "Reset at the start for each round, swap direction or load as programmed.",
    ],
  },
  {
    id: "landmine-squat",
    name: "Landmine Squat",
    category: "Full Body",
    muscleGroup: "Full Body",
    secondaryMuscles: ["Quads", "Glutes", "Core"],
    equipment: "Barbell",
    caloriesPerMinute: 8.5,
    instructions: [
      "Anchor a barbell in a landmine, grip the loaded end at chest height.",
      "Stand with feet shoulder-width, toes slightly out, elbows pinned in.",
      "Squat down with an upright torso, letting the bar arc in toward your chest.",
      "Drive up through your heels, keeping the bar hugged to your chest.",
    ],
  },
  {
    id: "zercher-squat",
    name: "Zercher Squat",
    category: "Full Body",
    muscleGroup: "Full Body",
    secondaryMuscles: ["Quads", "Glutes", "Biceps", "Core"],
    equipment: "Barbell",
    caloriesPerMinute: 9,
    instructions: [
      "Cradle the bar in the crooks of your elbows, hands clasped.",
      "Stand with feet shoulder-width, core braced hard.",
      "Squat down keeping the torso upright, elbows driving inside your knees.",
      "Drive up through your heels without letting the bar roll forward.",
    ],
    tip: "The bar will bruise your elbows if you go too heavy too fast. Use a sleeve or towel and build load slowly — this is a patience lift.",
  },
  {
    id: "turkish-get-up",
    name: "Turkish Get-Up",
    category: "Full Body",
    muscleGroup: "Full Body",
    secondaryMuscles: ["Shoulders", "Core", "Glutes"],
    equipment: "Kettlebell",
    caloriesPerMinute: 8,
    instructions: [
      "Lie on your back, kettlebell pressed straight up with one arm, eyes on the bell.",
      "Rise through a sequence: to elbow, to hand, to bridge, to kneeling, to standing.",
      "Keep the arm locked and bell vertical through every position.",
      "Reverse the sequence with the same control back to the start.",
    ],
    tip: "Eyes lock on the bell from start to finish. If you lose sight of it or the arm bends, stop the set — a falling bell on a shoulder ends seasons.",
  },
  {
    id: "man-maker",
    name: "Man Maker",
    category: "Full Body",
    muscleGroup: "Full Body",
    secondaryMuscles: ["Chest", "Shoulders", "Back", "Legs"],
    equipment: "Dumbbells",
    caloriesPerMinute: 11,
    instructions: [
      "Start in a high plank gripping dumbbells, body straight.",
      "Do a push-up, then row each dumbbell in turn to your ribs.",
      "Jump your feet forward to your hands and clean the dumbbells to your shoulders.",
      "Press overhead, then reverse back into plank for the next rep.",
    ],
  },
  {
    id: "battle-ropes",
    name: "Battle Ropes",
    category: "Full Body",
    muscleGroup: "Full Body",
    secondaryMuscles: ["Shoulders", "Arms", "Core"],
    equipment: "Battle Ropes",
    caloriesPerMinute: 11,
    instructions: [
      "Grip one end of the rope in each hand, stance wide, soft knees.",
      "Drop into a quarter squat and brace your core.",
      "Drive waves by alternating arms up and down at a fast pace.",
      "Keep the rhythm consistent — don't let the waves die at the anchor.",
    ],
  },
  {
    id: "box-jumps",
    name: "Box Jumps",
    category: "Full Body",
    muscleGroup: "Full Body",
    secondaryMuscles: ["Quads", "Glutes", "Calves"],
    equipment: "Box",
    caloriesPerMinute: 9,
    instructions: [
      "Stand facing a sturdy box, feet shoulder-width, soft knees.",
      "Dip into a quarter squat and swing your arms back for momentum.",
      "Explode up onto the box, landing softly with both feet at the same time.",
      "Stand fully upright on the box, then step down — don't jump down.",
    ],
    tip: "Jumping down trashes knees over time. Step down every rep — your joints will thank you ten years from now.",
  },

  // ================= CARDIO =================
  {
    id: "treadmill",
    name: "Treadmill",
    category: "Cardio",
    muscleGroup: "Cardio",
    secondaryMuscles: ["Quads", "Calves"],
    equipment: "Machine",
    caloriesPerMinute: 10,
    instructions: [
      "Step onto the belt and start at a slow walk to find your footing.",
      "Dial in your target speed and incline for the session.",
      "Run or walk with upright posture and a natural arm swing.",
      "Don't hold the handrails — let your arms drive the pace.",
    ],
  },
  {
    id: "incline-treadmill-walk",
    name: "Incline Treadmill Walking",
    category: "Cardio",
    muscleGroup: "Cardio",
    secondaryMuscles: ["Glutes", "Calves"],
    equipment: "Machine",
    caloriesPerMinute: 7,
    instructions: [
      "Set the incline between 10-15% and a moderate walking pace.",
      "Step onto the belt and settle into the grade without gripping the rails.",
      "Keep a slight forward lean from the ankles, not the hips.",
      "Let your arms swing naturally, glutes and calves doing the work.",
    ],
  },
  {
    id: "elliptical",
    name: "Elliptical",
    category: "Cardio",
    muscleGroup: "Cardio",
    secondaryMuscles: ["Quads", "Glutes"],
    equipment: "Machine",
    caloriesPerMinute: 8,
    instructions: [
      "Step on the pedals with feet evenly placed, grip the moving handles.",
      "Start with a smooth easy pace to find the stride rhythm.",
      "Push and pull with arms and legs together for full-body drive.",
      "Stand tall — no leaning on the console.",
    ],
  },
  {
    id: "rowing-machine",
    name: "Rowing Machine",
    category: "Cardio",
    muscleGroup: "Cardio",
    secondaryMuscles: ["Back", "Legs", "Core"],
    equipment: "Machine",
    caloriesPerMinute: 9,
    instructions: [
      "Strap in, grip the handle, start compressed with shins vertical.",
      "Drive with your legs first, then lean back, then pull the handle to your ribs.",
      "Return in reverse order: arms out, hinge forward, then slide the seat in.",
      "Keep the stroke rhythm smooth — 2:1 return to drive ratio.",
    ],
    tip: "If you're yanking the handle with your arms first, you're wasting the big engine. Legs, back, arms — in that order.",
  },
  {
    id: "stairmaster",
    name: "Stairmaster",
    category: "Cardio",
    muscleGroup: "Cardio",
    secondaryMuscles: ["Quads", "Glutes", "Calves"],
    equipment: "Machine",
    caloriesPerMinute: 9,
    instructions: [
      "Step on and set a steady pace you can sustain.",
      "Stand tall with shoulders stacked over hips, light grip on the rails.",
      "Climb with full steps — drive your whole foot down each time.",
      "Don't lean hard on the handles or you'll cut the work in half.",
    ],
  },
  {
    id: "bike",
    name: "Stationary Bike",
    category: "Cardio",
    muscleGroup: "Cardio",
    secondaryMuscles: ["Quads", "Hamstrings"],
    equipment: "Machine",
    caloriesPerMinute: 7.5,
    instructions: [
      "Adjust the seat so your leg has a slight bend at the bottom of the pedal.",
      "Sit with a neutral spine, grip the bars loosely.",
      "Pedal at a steady cadence, adjusting resistance to hit your target effort.",
      "Keep the cadence smooth — no yanking up on the stroke.",
    ],
  },
  {
    id: "spin-bike",
    name: "Spin Bike",
    category: "Cardio",
    muscleGroup: "Cardio",
    secondaryMuscles: ["Quads", "Hamstrings", "Core"],
    equipment: "Machine",
    caloriesPerMinute: 9,
    instructions: [
      "Dial in seat and bar height — seat level with the bars for most.",
      "Clip or strap in, grip the bars with a firm but relaxed hold.",
      "Pedal at a high cadence, alternating seated and standing drives.",
      "Match resistance to the effort — no flying pedals at max RPM.",
    ],
  },
  {
    id: "assault-bike",
    name: "Assault Bike",
    category: "Cardio",
    muscleGroup: "Cardio",
    secondaryMuscles: ["Full Body"],
    equipment: "Machine",
    caloriesPerMinute: 12,
    instructions: [
      "Adjust the seat so your legs extend almost straight at the bottom.",
      "Grip the moving handles, place feet on the pedals.",
      "Push and pull with the arms while driving the pedals hard.",
      "Breathe rhythmically — this burns out fast if you hold your breath.",
    ],
  },
  {
    id: "ski-erg",
    name: "Ski Erg",
    category: "Cardio",
    muscleGroup: "Cardio",
    secondaryMuscles: ["Lats", "Core", "Triceps"],
    equipment: "Machine",
    caloriesPerMinute: 10,
    instructions: [
      "Stand facing the machine, grip both handles overhead, soft knees.",
      "Hinge at the hips and pull the handles down past your thighs.",
      "Drive through your core and lats — not just your arms.",
      "Stand up and reach overhead smoothly for the next pull.",
    ],
  },
  {
    id: "jump-rope",
    name: "Jump Rope",
    category: "Cardio",
    muscleGroup: "Cardio",
    secondaryMuscles: ["Calves", "Shoulders"],
    equipment: "Jump Rope",
    caloriesPerMinute: 11,
    instructions: [
      "Hold handles at your hips, elbows pinned close to your ribs.",
      "Start with small wrist flicks to turn the rope, not big arm swings.",
      "Jump just an inch or two off the floor — enough to clear the rope.",
      "Land softly on the balls of your feet and stay relaxed.",
    ],
  },
  {
    id: "swimming",
    name: "Swimming",
    category: "Cardio",
    muscleGroup: "Cardio",
    secondaryMuscles: ["Full Body"],
    equipment: "Pool",
    caloriesPerMinute: 9,
    instructions: [
      "Pick your stroke and start with an easy warm-up length.",
      "Focus on a streamlined body position — hips at the surface.",
      "Breathe on a consistent rhythm for the stroke you're using.",
      "Swim continuous laps at your target effort, resting on the wall as programmed.",
    ],
  },

  // ================= ADDITIONAL EXERCISES =================
  {
    id: "dips",
    name: "Dips",
    category: "Chest",
    muscleGroup: "Pectorals",
    secondaryMuscles: ["Triceps", "Front Delts"],
    equipment: "Bodyweight",
    caloriesPerMinute: 7.5,
    instructions: [
      "Grip parallel bars with arms locked, chest tall, core braced.",
      "Lean your torso forward about 30° to emphasise the chest.",
      "Lower with elbows tracking slightly out until upper arms are parallel to the floor.",
      "Press back up to full lockout, keeping the forward lean locked.",
    ],
    tip: "Shoulder pain at the bottom means you're going too deep for your mobility. Stop at parallel and only go deeper if the joint stays happy.",
  },
  {
    id: "muscle-ups",
    name: "Muscle-Ups",
    category: "Full Body",
    muscleGroup: "Full Body",
    secondaryMuscles: ["Lats", "Chest", "Triceps", "Core"],
    equipment: "Bodyweight",
    caloriesPerMinute: 9.5,
    instructions: [
      "Hang from the bar with a false (thumbless) overhand grip.",
      "Pull yourself up explosively, leaning back and pulling hard.",
      "Roll your wrists forward over the bar as chest passes it.",
      "Press up to full lockout above the bar, then lower with control.",
    ],
    tip: "The wrist roll is the whole lift. If you can't get your chest over the bar without the roll, keep practising high pull-ups until you can.",
  },
  {
    id: "handstand-push-ups",
    name: "Handstand Push-Ups",
    category: "Shoulders",
    muscleGroup: "Deltoids",
    secondaryMuscles: ["Triceps", "Traps", "Core"],
    equipment: "Bodyweight",
    caloriesPerMinute: 8,
    instructions: [
      "Kick into a handstand against a wall, arms locked, body stacked.",
      "Brace your core so hips don't flare off the wall.",
      "Lower by bending your elbows until the top of your head touches the floor.",
      "Press back up to full arm extension, keeping the line tight.",
    ],
    tip: "Build up with pike push-ups and negatives first. A collapse into the floor on your skull is not a rep you recover from quickly.",
  },
  {
    id: "cable-fly",
    name: "Cable Fly",
    category: "Chest",
    muscleGroup: "Pectorals",
    secondaryMuscles: ["Front Delts"],
    equipment: "Cable Machine",
    caloriesPerMinute: 5.5,
    instructions: [
      "Set pulleys at chest height, grab a handle in each hand, step forward.",
      "Set a soft bend in your elbows and lock the angle for the set.",
      "Bring your hands together in front of your chest in a wide arc.",
      "Open slowly to a full chest stretch without losing the elbow angle.",
    ],
  },
];

export function getExercisesByCategory(category: string): Exercise[] {
  return EXERCISES.filter((e) => e.category === category);
}

// O(1) id → exercise lookup. getExerciseById is called inside the
// render path of WorkoutSession + Program tab (typically 8-12 calls
// per render against a 2400-entry array) — replacing the linear
// `find` with a Map cuts ~20k string comparisons per render to one.
const EXERCISES_BY_ID = new Map(EXERCISES.map((e) => [e.id, e]));

export function getExerciseById(id: string): Exercise | undefined {
  return EXERCISES_BY_ID.get(id);
}

/**
 * True iff the exercise is *intrinsically* bodyweight (Pull-Ups, Dips,
 * Push-Ups, etc. — `equipment === "Bodyweight"`).
 *
 * This is the correct check for distinguishing "this is a bodyweight
 * movement" from "this exercise doesn't have a calibrated working
 * weight yet." A new Lat Pulldown has `weight: 0` but is NOT
 * bodyweight — the 0 means uncalibrated, not BW. Treating
 * `weight === 0` as BW (the previous default) silently labelled
 * weighted exercises as "BW" in history and progress charts, dragging
 * 1RM charts to 0 on uncalibrated days.
 *
 * Use this everywhere a BW vs weighted decision is made:
 *   - Display ("BW × 10" vs "30 kg × 10")
 *   - Progression (add reps for BW; add load for weighted)
 *   - PR detection
 *   - Volume calculation
 */
export function isBodyweightExerciseId(
  exerciseId: string | undefined
): boolean {
  if (!exerciseId) return false;
  return getExerciseById(exerciseId)?.equipment === "Bodyweight";
}

export function estimateCalories(
  exerciseId: string,
  sets: number,
  reps: number,
  weightKg: number
): number {
  const exercise = getExerciseById(exerciseId);
  if (!exercise) return 0;
  const minutesPerSet = (reps * 3) / 60 + 1;
  const totalMinutes = minutesPerSet * sets;
  const weightMultiplier = 1 + (weightKg / 100) * 0.3;
  return Math.round(
    exercise.caloriesPerMinute * totalMinutes * weightMultiplier
  );
}
