export interface Exercise {
  id: string;
  name: string;
  category: string;
  muscleGroup: string;
  secondaryMuscles?: string[];
  equipment: string;
  caloriesPerMinute: number;
  instructions?: string[];
  tip?: string;
}

export const EXERCISE_CATEGORIES = [
  "Chest",
  "Back",
  "Shoulders",
  "Biceps",
  "Triceps",
  "Legs",
  "Core",
  "Full Body",
  "Cardio",
] as const;

export const EXERCISES: Exercise[] = [
  // ================= CHEST =================
  {
    id: "bench-press",
    name: "Bench Press",
    category: "Chest",
    muscleGroup: "Pectorals",
    secondaryMuscles: ["Triceps", "Front Delts"],
    equipment: "Barbell",
    caloriesPerMinute: 7.5,
    instructions: [
      "Lie flat, feet planted, eyes directly under the bar.",
      "Pinch your shoulder blades hard into the bench and grip slightly wider than shoulders.",
      "Unrack, then lower the bar to your mid-chest with elbows at about 45° from your torso.",
      "Drive the bar up and slightly back over your shoulders to full lockout.",
    ],
    tip: "Flared elbows (straight out at 90°) are how shoulders get wrecked. If you can't hold the 45° tuck, drop weight and fix the groove.",
  },
  {
    id: "incline-bench",
    name: "Incline Bench Press",
    category: "Chest",
    muscleGroup: "Upper Chest",
    secondaryMuscles: ["Triceps", "Front Delts"],
    equipment: "Barbell",
    caloriesPerMinute: 7.5,
    instructions: [
      "Set the bench to 30°, feet flat, eyes under the bar.",
      "Retract your shoulder blades into the pad and grip slightly wider than shoulders.",
      "Lower the bar to your upper chest, elbows tracking around 45° from your torso.",
      "Press up and slightly back, squeezing the upper chest at lockout.",
    ],
    tip: "Cranking the bench above 45° turns this into a front-delt press. Keep the incline low or you're not training upper chest.",
  },
  {
    id: "decline-bench",
    name: "Decline Bench Press",
    category: "Chest",
    muscleGroup: "Lower Chest",
    secondaryMuscles: ["Triceps", "Front Delts"],
    equipment: "Barbell",
    caloriesPerMinute: 7.5,
    instructions: [
      "Lock your feet in, pinch shoulder blades, grip slightly wider than shoulders.",
      "Unrack with a tight brace and stack the bar over your lower chest.",
      "Lower with control until the bar lightly touches your lower chest.",
      "Press up and slightly back, finishing with elbows stacked over shoulders.",
    ],
  },
  {
    id: "db-bench",
    name: "Dumbbell Bench Press",
    category: "Chest",
    muscleGroup: "Pectorals",
    secondaryMuscles: ["Triceps", "Front Delts"],
    equipment: "Dumbbells",
    caloriesPerMinute: 7,
    instructions: [
      "Sit on a flat bench with dumbbells resting on your thighs.",
      "Kick the weights up to shoulder height and lie back, palms facing forward.",
      "Press the dumbbells up until arms are straight, letting them drift slightly inward.",
      "Lower under control to a deep chest stretch with elbows at about 45°.",
    ],
  },
  {
    id: "incline-db-press",
    name: "Incline Dumbbell Press",
    category: "Chest",
    muscleGroup: "Upper Chest",
    secondaryMuscles: ["Triceps", "Front Delts"],
    equipment: "Dumbbells",
    caloriesPerMinute: 7,
    instructions: [
      "Set the bench to 30° and sit with dumbbells on your thighs.",
      "Kick the weights to shoulder height and lie back, palms facing forward.",
      "Press the dumbbells up and slightly in until they nearly touch at the top.",
      "Lower slowly to a full stretch on the upper chest.",
    ],
  },
  {
    id: "decline-db-press",
    name: "Decline Dumbbell Press",
    category: "Chest",
    muscleGroup: "Lower Chest",
    secondaryMuscles: ["Triceps", "Front Delts"],
    equipment: "Dumbbells",
    caloriesPerMinute: 7,
    instructions: [
      "Secure your legs on a decline bench with dumbbells at chest level.",
      "Keep your shoulder blades pinned and brace your core hard.",
      "Press the dumbbells up to full extension, arcing them slightly inward.",
      "Lower with control until you feel a deep stretch across your lower chest.",
    ],
  },
  {
    id: "db-flyes",
    name: "Dumbbell Flyes",
    category: "Chest",
    muscleGroup: "Pectorals",
    secondaryMuscles: ["Front Delts"],
    equipment: "Dumbbells",
    caloriesPerMinute: 5,
    instructions: [
      "Lie flat with dumbbells pressed straight up over your chest.",
      "Set a soft bend in your elbows — lock that angle, don't change it.",
      "Lower the weights in a wide arc until you feel a stretch across your chest.",
      "Squeeze your chest to bring the dumbbells back together above your chest.",
    ],
    tip: "Too much weight turns this into a sloppy press as the elbow angle collapses. If the angle opens up, drop weight and own the stretch.",
  },
  {
    id: "cable-crossover",
    name: "Cable Crossover",
    category: "Chest",
    muscleGroup: "Pectorals",
    secondaryMuscles: ["Front Delts"],
    equipment: "Cable Machine",
    caloriesPerMinute: 5.5,
    instructions: [
      "Set both pulleys high, grab a handle in each hand with palms facing down.",
      "Step forward with a slight forward lean and a soft bend at the elbows.",
      "Pull the handles down and together in front of your hips in a wide arc.",
      "Squeeze hard at the bottom, then return slowly to the stretched start.",
    ],
  },
  {
    id: "chest-press-machine",
    name: "Chest Press Machine",
    category: "Chest",
    muscleGroup: "Pectorals",
    secondaryMuscles: ["Triceps", "Front Delts"],
    equipment: "Machine",
    caloriesPerMinute: 6,
    instructions: [
      "Adjust the seat so the handles sit level with your mid-chest.",
      "Pin your back to the pad and plant your feet firmly on the floor.",
      "Press the handles forward until your arms are fully extended.",
      "Return slowly under control, stopping just before the stack touches down.",
    ],
  },
  {
    id: "pec-deck",
    name: "Pec Deck",
    category: "Chest",
    muscleGroup: "Pectorals",
    secondaryMuscles: ["Front Delts"],
    equipment: "Machine",
    caloriesPerMinute: 5,
    instructions: [
      "Sit with your back flat against the pad, feet firmly on the floor.",
      "Place your forearms on the pads with elbows at shoulder height.",
      "Squeeze the pads together in front of your chest, pausing at the peak.",
      "Open slowly to a full stretch without letting the stack touch down.",
    ],
  },
  {
    id: "machine-chest-fly",
    name: "Machine Chest Fly",
    category: "Chest",
    muscleGroup: "Chest",
    secondaryMuscles: ["Front Delts"],
    equipment: "Machine",
    caloriesPerMinute: 5.5,
    instructions: [
      "Sit with your back flat and grip the handles at chest height.",
      "Set a soft bend in your elbows and lock that angle for the whole set.",
      "Bring the handles together in front of your chest, squeezing hard at the peak.",
      "Open slowly to the starting position, controlling the stretch at the end.",
    ],
  },
  {
    id: "smith-bench-press",
    name: "Smith Machine Bench Press",
    category: "Chest",
    muscleGroup: "Chest",
    secondaryMuscles: ["Triceps", "Front Delts"],
    equipment: "Machine",
    caloriesPerMinute: 7,
    instructions: [
      "Line up a flat bench so the bar lands over your mid-chest when unracked.",
      "Grip slightly wider than shoulders and rotate the hooks off.",
      "Lower the bar to your chest with elbows tracking around 45° from your torso.",
      "Press back up to lockout without bouncing the bar off your chest.",
    ],
    tip: "The fixed bar path means any rig misalignment hits your shoulders directly. If the bar doesn't track straight down to mid-chest, reset the bench.",
  },
  {
    id: "push-ups",
    name: "Push-Ups",
    category: "Chest",
    muscleGroup: "Pectorals",
    secondaryMuscles: ["Triceps", "Front Delts", "Core"],
    equipment: "Bodyweight",
    caloriesPerMinute: 7,
    instructions: [
      "Start in a high plank, hands slightly wider than shoulders, body in a straight line.",
      "Lower your chest toward the floor, elbows tracking at about 45° from your sides.",
      "Pause just above the ground, then press back up to full extension.",
      "Keep your abs tight the whole time — no sagging hips.",
    ],
    tip: "Flared elbows (90° out) wreck your shoulders over time. If you can't hold the 45° angle, drop to knees and build up.",
  },
  {
    id: "pike-push-up",
    name: "Pike Push-Up",
    category: "Shoulders",
    muscleGroup: "Deltoids",
    secondaryMuscles: ["Triceps", "Upper Chest"],
    equipment: "Bodyweight",
    caloriesPerMinute: 6.5,
    instructions: [
      "Start in a downward-dog with hands shoulder-width and hips stacked high.",
      "Walk your feet in so your torso is nearly vertical over your hands.",
      "Bend your elbows and lower the crown of your head toward the floor.",
      "Press back up to straight arms, keeping your hips piked high throughout.",
    ],
    tip: "If your hips drift forward, it turns into a regular push-up and the shoulders stop working. Keep the pike tight or shorten the range.",
  },
  {
    id: "weighted-push-ups",
    name: "Weighted Push-Ups",
    category: "Chest",
    muscleGroup: "Chest",
    secondaryMuscles: ["Triceps", "Front Delts", "Core"],
    equipment: "Bodyweight",
    caloriesPerMinute: 8,
    instructions: [
      "Set a plate on your upper back or wear a weighted vest, then get into a high plank.",
      "Hands slightly wider than shoulders, body in a straight line from head to heels.",
      "Lower with control, elbows at 45°, until your chest is an inch off the floor.",
      "Press back up to full lockout without letting the weight shift.",
    ],
    tip: "A sliding plate wrecks the set and can hit your spine. Have a partner place it high on your shoulder blades, or switch to a vest.",
  },
  {
    id: "barbell-floor-press",
    name: "Barbell Floor Press",
    category: "Chest",
    muscleGroup: "Chest",
    secondaryMuscles: ["Triceps", "Front Delts"],
    equipment: "Barbell",
    caloriesPerMinute: 7,
    instructions: [
      "Lie on the floor under a rack, bar positioned over your mid-chest.",
      "Grip slightly wider than shoulders and plant your feet or bend your knees.",
      "Lower the bar until your upper arms touch the floor, pause for a beat.",
      "Drive the bar back up to full lockout, treating the pause as a hard reset.",
    ],
  },
  {
    id: "weighted-chest-dip",
    name: "Weighted Chest Dip",
    category: "Chest",
    muscleGroup: "Lower Chest",
    secondaryMuscles: ["Triceps", "Front Delts"],
    equipment: "Bodyweight",
    caloriesPerMinute: 8,
    instructions: [
      "Attach a dip belt or pinch a dumbbell between your feet on parallel bars.",
      "Lean your torso forward about 30° and keep a slight bend in your knees.",
      "Lower until your upper arms are parallel to the floor, chest stretched.",
      "Press back up to the top, keeping the forward lean locked throughout.",
    ],
    tip: "Going below parallel with rounded shoulders is how people tear pecs. If your shoulders feel bad mid-rep, rack the weights — don't train through it.",
  },

  // ================= BACK =================
  { id: "deadlift", name: "Deadlift", category: "Back", muscleGroup: "Full Back", secondaryMuscles: ["Glutes", "Hamstrings", "Core", "Traps"], equipment: "Barbell", caloriesPerMinute: 9, instructions: ["Stand with feet hip-width apart, barbell over mid-foot. Hinge at the hips, grip the bar just outside your knees, and drive through the floor to stand up. Keep your back flat, chest up, and the bar close to your body throughout."] },
  { id: "barbell-row", name: "Barbell Row", category: "Back", muscleGroup: "Lats", secondaryMuscles: ["Rhomboids", "Rear Delts", "Biceps"], equipment: "Barbell", caloriesPerMinute: 7, instructions: ["Hinge at the hips with a slight knee bend, holding the barbell with an overhand grip. Pull the bar toward your lower chest, squeezing your shoulder blades together at the top. Lower the bar under control and repeat."] },
  { id: "pendlay-row", name: "Pendlay Row", category: "Back", muscleGroup: "Lats", secondaryMuscles: ["Rhomboids", "Rear Delts", "Biceps", "Core"], equipment: "Barbell", caloriesPerMinute: 7.5, instructions: ["Set up with your torso parallel to the floor and the barbell on the ground. Explosively row the bar to your lower chest, then lower it back to the floor for a dead stop. Keep your back flat and reset between each rep."] },
  { id: "db-row", name: "Dumbbell Row", category: "Back", muscleGroup: "Lats", secondaryMuscles: ["Rhomboids", "Rear Delts", "Biceps"], equipment: "Dumbbells", caloriesPerMinute: 6.5, instructions: ["Place one hand and knee on a bench for support, holding a dumbbell in the other hand. Pull the dumbbell toward your hip, squeezing your lat at the top. Lower it under control and repeat before switching sides."] },
  { id: "chest-supported-db-row", name: "Chest-Supported Dumbbell Row", category: "Back", muscleGroup: "Mid Back", secondaryMuscles: ["Rhomboids", "Rear Delts", "Biceps"], equipment: "Dumbbells", caloriesPerMinute: 6.5, instructions: ["Lie face down on an incline bench set to 30-45 degrees, holding a dumbbell in each hand. Row both dumbbells toward your hips, squeezing your shoulder blades together. Lower under control, allowing a full stretch at the bottom."] },
  { id: "meadows-row", name: "Meadows Row", category: "Back", muscleGroup: "Lats", secondaryMuscles: ["Rhomboids", "Rear Delts", "Biceps"], equipment: "Barbell", caloriesPerMinute: 6.5, instructions: ["Stand perpendicular to a landmine attachment and stagger your stance. Grip the end of the barbell with an overhand grip and row it toward your hip. Focus on driving your elbow back and squeezing your lat at the top."] },
  { id: "pull-ups", name: "Pull-Ups", category: "Back", muscleGroup: "Lats", secondaryMuscles: ["Biceps", "Rear Delts", "Core"], equipment: "Bodyweight", caloriesPerMinute: 8, instructions: ["Hang from a pull-up bar with an overhand grip slightly wider than shoulder-width. Pull yourself up until your chin clears the bar, then lower back down with control. Avoid swinging and keep your core engaged throughout."] },
  { id: "chin-ups", name: "Chin-Ups", category: "Back", muscleGroup: "Lats", secondaryMuscles: ["Biceps", "Core"], equipment: "Bodyweight", caloriesPerMinute: 8, instructions: ["Hang from a bar with an underhand grip at shoulder-width. Pull yourself up until your chin clears the bar, engaging your lats and biceps. Lower yourself under control to a full dead hang and repeat."] },
  { id: "lat-pulldown", name: "Lat Pulldown", category: "Back", muscleGroup: "Lats", secondaryMuscles: ["Biceps", "Rear Delts"], equipment: "Cable Machine", caloriesPerMinute: 6, instructions: ["Sit at a lat pulldown machine and grip the bar wider than shoulder-width. Pull the bar down to your upper chest, squeezing your lats at the bottom. Slowly return the bar to the starting position with control."] },
  { id: "single-arm-lat-pulldown", name: "Single-Arm Lat Pulldown", category: "Back", muscleGroup: "Lats", secondaryMuscles: ["Biceps", "Rear Delts"], equipment: "Cable Machine", caloriesPerMinute: 6, instructions: ["Attach a single handle to a high pulley and sit or kneel at the cable station. Pull the handle down toward your side, focusing on contracting your lat. Return to the top under control and complete all reps before switching sides."] },
  { id: "seated-row", name: "Seated Cable Row", category: "Back", muscleGroup: "Mid Back", secondaryMuscles: ["Rhomboids", "Biceps", "Rear Delts"], equipment: "Cable Machine", caloriesPerMinute: 6, instructions: ["Sit at a cable row station with your feet on the platform and knees slightly bent. Pull the handle toward your lower chest, squeezing your shoulder blades together. Slowly extend your arms back without rounding your back."] },
  { id: "t-bar-row", name: "T-Bar Row", category: "Back", muscleGroup: "Mid Back", secondaryMuscles: ["Lats", "Rhomboids", "Biceps"], equipment: "Barbell", caloriesPerMinute: 7, instructions: ["Straddle the T-bar row machine or landmine setup and grip the handles. With your torso at roughly 45 degrees, row the weight toward your chest. Squeeze your back at the top and lower the weight under control."] },
  { id: "face-pulls", name: "Face Pulls", category: "Back", muscleGroup: "Rear Delts", secondaryMuscles: ["Rhomboids", "Traps", "Rotator Cuff"], equipment: "Cable Machine", caloriesPerMinute: 4.5, instructions: ["Attach a rope to a high cable pulley. Pull toward your face, separating the rope ends past your ears. Squeeze your rear delts and external rotators at the peak."] },
  { id: "rack-pull", name: "Rack Pull", category: "Back", muscleGroup: "Posterior Chain", secondaryMuscles: ["Traps", "Glutes", "Core"], equipment: "Barbell", caloriesPerMinute: 8.5, instructions: ["Set the barbell on safety pins in a power rack at knee height. Grip the bar, brace your core, and stand up by driving your hips forward. Lower the bar back to the pins under control, keeping your back straight."] },
  { id: "straight-arm-pulldown", name: "Straight-Arm Pulldown", category: "Back", muscleGroup: "Lats", secondaryMuscles: ["Teres Major", "Core"], equipment: "Cable Machine", caloriesPerMinute: 5.5, instructions: ["Stand facing a high cable pulley and grip the bar with straight arms. Push the bar down in an arc toward your thighs, keeping your arms straight and squeezing your lats. Slowly return to the starting position."] },
  { id: "inverted-row", name: "Inverted Row", category: "Back", muscleGroup: "Mid Back", secondaryMuscles: ["Rhomboids", "Biceps", "Core"], equipment: "Bodyweight", caloriesPerMinute: 7, instructions: ["Set a barbell in a rack at waist height and hang underneath it with an overhand grip. Pull your chest up to the bar, squeezing your shoulder blades together. Lower yourself back down with control, keeping your body straight."] },

  // ================= SHOULDERS =================
  { id: "overhead-press", name: "Overhead Press", category: "Shoulders", muscleGroup: "Deltoids", secondaryMuscles: ["Triceps", "Upper Chest", "Core"], equipment: "Barbell", caloriesPerMinute: 7, instructions: ["Stand with feet shoulder-width apart, holding the barbell at shoulder height. Press the bar overhead until your arms are fully extended, moving your head forward once the bar passes. Lower the bar back to your shoulders under control."] },
  { id: "db-shoulder-press", name: "Dumbbell Shoulder Press", category: "Shoulders", muscleGroup: "Deltoids", secondaryMuscles: ["Triceps", "Upper Chest"], equipment: "Dumbbells", caloriesPerMinute: 6.5, instructions: ["Sit or stand holding dumbbells at shoulder height with palms facing forward. Press both dumbbells overhead until your arms are fully extended. Lower them back to shoulder height under control."] },
  { id: "lateral-raise", name: "Lateral Raise", category: "Shoulders", muscleGroup: "Side Delts", secondaryMuscles: ["Traps"], equipment: "Dumbbells", caloriesPerMinute: 4.5, instructions: ["Stand with dumbbells at your sides, palms facing inward. Raise both arms out to the sides until they reach shoulder height, keeping a slight bend in your elbows. Lower them back down slowly under control."] },
  { id: "reverse-pec-deck", name: "Reverse Pec Deck", category: "Shoulders", muscleGroup: "Rear Delts", secondaryMuscles: ["Traps", "Rhomboids"], equipment: "Machine", caloriesPerMinute: 4.5, instructions: ["Sit facing the pec deck with your chest against the pad and grip the handles with arms extended in front of you. Pull your arms back and out to the sides, squeezing your rear delts at the end range. Return to the starting position under control."] },
  { id: "cable-lateral-raise", name: "Cable Lateral Raise", category: "Shoulders", muscleGroup: "Side Delts", secondaryMuscles: ["Traps"], equipment: "Cable Machine", caloriesPerMinute: 4.5, instructions: ["Stand sideways to a low cable pulley and grab the handle with your far hand. Raise your arm out to the side until it reaches shoulder height, keeping a slight elbow bend. Lower under control and complete all reps before switching sides."] },
  { id: "front-raise", name: "Front Raise", category: "Shoulders", muscleGroup: "Front Delts", secondaryMuscles: ["Upper Chest"], equipment: "Dumbbells", caloriesPerMinute: 4.5, instructions: ["Stand holding dumbbells in front of your thighs with palms facing your body. Raise one or both arms straight in front of you to shoulder height. Lower under control and repeat."] },
  { id: "reverse-flyes", name: "Reverse Flyes", category: "Shoulders", muscleGroup: "Rear Delts", secondaryMuscles: ["Rhomboids", "Traps"], equipment: "Dumbbells", caloriesPerMinute: 4.5, instructions: ["Bend forward at the hips holding dumbbells with palms facing each other. Raise the dumbbells out to the sides, squeezing your rear delts and upper back. Lower them back down slowly and repeat."] },
  { id: "rear-delt-machine-fly", name: "Rear Delt Machine Fly", category: "Shoulders", muscleGroup: "Rear Delts", secondaryMuscles: ["Rhomboids", "Traps"], equipment: "Machine", caloriesPerMinute: 4.5, instructions: ["Sit facing the pec deck machine and grip the handles at chest height. Push the handles apart by squeezing your rear delts, opening your arms wide. Return to the starting position under control."] },
  { id: "arnold-press", name: "Arnold Press", category: "Shoulders", muscleGroup: "Deltoids", secondaryMuscles: ["Triceps", "Upper Chest"], equipment: "Dumbbells", caloriesPerMinute: 6.5, instructions: ["Start with dumbbells at shoulder height, palms facing you. As you press overhead, rotate your palms to face forward at the top. Reverse the motion on the way down, rotating your palms back toward you."] },
  { id: "shoulder-press-machine", name: "Shoulder Press Machine", category: "Shoulders", muscleGroup: "Deltoids", secondaryMuscles: ["Triceps"], equipment: "Machine", caloriesPerMinute: 6, instructions: ["Adjust the seat so the handles are at shoulder height. Grip the handles and press upward until your arms are fully extended. Lower back to the starting position under control."] },
  { id: "smith-shoulder-press", name: "Smith Machine Shoulder Press", category: "Shoulders", muscleGroup: "Deltoids", secondaryMuscles: ["Triceps", "Upper Chest"], equipment: "Machine", caloriesPerMinute: 6.5, instructions: ["Sit on a bench positioned under the Smith machine bar. Unrack the bar at shoulder height and press it overhead to full lockout. Lower the bar back to shoulder height under control."] },
  { id: "barbell-upright-row", name: "Barbell Upright Row", category: "Shoulders", muscleGroup: "Traps", secondaryMuscles: ["Side Delts", "Biceps"], equipment: "Barbell", caloriesPerMinute: 6, instructions: ["Stand holding a barbell with a shoulder-width or narrower grip in front of your thighs. Pull the bar straight up along your body to chest height, leading with your elbows. Lower the bar back down under control."] },
  { id: "shrugs", name: "Shrugs", category: "Shoulders", muscleGroup: "Traps", secondaryMuscles: [], equipment: "Dumbbells", caloriesPerMinute: 5, instructions: ["Stand holding dumbbells at your sides with arms straight. Shrug your shoulders straight up toward your ears, squeezing your traps at the top. Lower your shoulders back down under control."] },
  { id: "barbell-shrug", name: "Barbell Shrug", category: "Shoulders", muscleGroup: "Traps", secondaryMuscles: ["Forearms"], equipment: "Barbell", caloriesPerMinute: 5.5, instructions: ["Stand holding a barbell in front of your thighs with an overhand grip and arms straight. Shrug your shoulders straight up toward your ears, squeezing your traps at the top. Lower the bar back down under control, avoiding a rolling shoulder motion."] },
  { id: "cuban-press", name: "Cuban Press", category: "Shoulders", muscleGroup: "Shoulders", secondaryMuscles: ["Rotator Cuff", "Traps"], equipment: "Dumbbells", caloriesPerMinute: 5, instructions: ["Start with dumbbells hanging in front of you. Perform an upright row, then externally rotate your shoulders so the dumbbells point up, and press overhead. Reverse the sequence to return to the starting position."] },
  { id: "lu-raise", name: "Lu Raise", category: "Shoulders", muscleGroup: "Deltoids", secondaryMuscles: ["Front Delts", "Side Delts"], equipment: "Dumbbells", caloriesPerMinute: 5, instructions: ["Hold light dumbbells at your sides. Perform a lateral raise, then at the top rotate the dumbbells forward and bring them together in front of you. Reverse the movement to return to the starting position."] },
  { id: "landmine-press", name: "Landmine Press", category: "Shoulders", muscleGroup: "Deltoids", secondaryMuscles: ["Upper Chest", "Triceps", "Core"], equipment: "Barbell", caloriesPerMinute: 6.5, instructions: ["Stand holding the end of a barbell anchored in a landmine attachment at shoulder height. Press the bar up and forward until your arm is fully extended. Lower it back to your shoulder under control."] },

  // ================= BICEPS =================
  { id: "barbell-curl", name: "Barbell Curl", category: "Biceps", muscleGroup: "Biceps", secondaryMuscles: ["Forearms"], equipment: "Barbell", caloriesPerMinute: 5, instructions: ["Stand holding a barbell with an underhand grip at shoulder-width. Curl the bar up toward your shoulders, keeping your elbows pinned to your sides. Lower the bar back down under control without swinging."] },
  { id: "ez-bar-curl", name: "EZ Bar Curl", category: "Biceps", muscleGroup: "Biceps", secondaryMuscles: ["Forearms"], equipment: "Barbell", caloriesPerMinute: 5, instructions: ["Hold an EZ curl bar on the angled grips with an underhand grip. Curl the bar up to shoulder height, keeping your elbows stationary. Lower it back down slowly and repeat."] },
  { id: "db-curl", name: "Dumbbell Curl", category: "Biceps", muscleGroup: "Biceps", secondaryMuscles: ["Forearms"], equipment: "Dumbbells", caloriesPerMinute: 5, instructions: ["Stand holding dumbbells at your sides with palms facing forward. Curl both dumbbells up toward your shoulders, keeping your elbows close to your body. Lower them back down under control."] },
  { id: "incline-db-curl", name: "Incline Dumbbell Curl", category: "Biceps", muscleGroup: "Biceps", secondaryMuscles: ["Forearms"], equipment: "Dumbbells", caloriesPerMinute: 5, instructions: ["Sit on an incline bench set to about 45 degrees, holding dumbbells with arms hanging straight. Curl the dumbbells up toward your shoulders without moving your upper arms. Lower them back down slowly to get a full stretch."] },
  { id: "hammer-curl", name: "Hammer Curl", category: "Biceps", muscleGroup: "Biceps", secondaryMuscles: ["Brachioradialis", "Forearms"], equipment: "Dumbbells", caloriesPerMinute: 5, instructions: ["Stand holding dumbbells at your sides with palms facing each other. Curl both dumbbells up toward your shoulders, maintaining the neutral grip throughout. Lower them back down under control."] },
  { id: "cross-body-hammer-curl", name: "Cross-Body Hammer Curl", category: "Biceps", muscleGroup: "Biceps", secondaryMuscles: ["Brachioradialis", "Forearms"], equipment: "Dumbbells", caloriesPerMinute: 5, instructions: ["Stand holding dumbbells at your sides with a neutral grip. Curl one dumbbell across your body toward the opposite shoulder. Lower it back down and alternate arms."] },
  { id: "zottman-curl", name: "Zottman Curl", category: "Biceps", muscleGroup: "Biceps", secondaryMuscles: ["Brachioradialis", "Forearms"], equipment: "Dumbbells", caloriesPerMinute: 5, instructions: ["Start with palms facing up and curl the dumbbells to the top. At the top, rotate your wrists so palms face down, then lower with this overhand grip. Rotate your palms back up at the bottom and repeat."] },
  { id: "preacher-curl", name: "Preacher Curl", category: "Biceps", muscleGroup: "Biceps", secondaryMuscles: ["Forearms"], equipment: "Barbell", caloriesPerMinute: 4.5, instructions: ["Sit at a preacher curl bench and place your upper arms flat on the pad. Grip the barbell with an underhand grip and curl it up toward your shoulders. Lower the bar back down slowly, keeping your arms on the pad."] },
  { id: "cable-curl", name: "Cable Curl", category: "Biceps", muscleGroup: "Biceps", secondaryMuscles: ["Forearms"], equipment: "Cable Machine", caloriesPerMinute: 4.5, instructions: ["Stand facing a low cable pulley with a straight bar or EZ bar attachment. Curl the bar up toward your shoulders, keeping your elbows at your sides. Lower back down under control, maintaining constant tension."] },
  { id: "bayesian-cable-curl", name: "Bayesian Cable Curl", category: "Biceps", muscleGroup: "Biceps", secondaryMuscles: ["Forearms"], equipment: "Cable Machine", caloriesPerMinute: 4.5, instructions: ["Face away from a low cable pulley, holding the handle with one hand behind you. Curl your hand forward and up toward your shoulder, keeping your elbow behind your torso. Lower under control for a deep bicep stretch."] },
  { id: "concentration-curl", name: "Concentration Curl", category: "Biceps", muscleGroup: "Biceps", secondaryMuscles: ["Forearms"], equipment: "Dumbbells", caloriesPerMinute: 4, instructions: ["Sit on a bench and brace the back of your upper arm against your inner thigh. Curl the dumbbell up toward your shoulder, squeezing your bicep at the top. Lower it back down slowly and repeat before switching arms."] },
  { id: "spider-db-curl", name: "Spider Dumbbell Curl", category: "Biceps", muscleGroup: "Biceps", secondaryMuscles: ["Forearms"], equipment: "Dumbbells", caloriesPerMinute: 4.5, instructions: ["Lie face down on an incline bench with your arms hanging straight down. Curl the dumbbells up toward your shoulders, keeping your upper arms stationary. Lower them back down for a full stretch and repeat."] },
  { id: "reverse-barbell-curl", name: "Reverse Barbell Curl", category: "Biceps", muscleGroup: "Biceps", secondaryMuscles: ["Brachioradialis", "Forearms"], equipment: "Barbell", caloriesPerMinute: 4.5, instructions: ["Stand holding a barbell with an overhand (pronated) grip at shoulder-width. Curl the bar up toward your shoulders, keeping your elbows pinned to your sides. Lower the bar back down under control."] },

  // ================= TRICEPS =================
  { id: "rope-tricep-pushdown", name: "Rope Tricep Pushdown", category: "Triceps", muscleGroup: "Triceps", secondaryMuscles: ["Forearms"], equipment: "Cable Machine", caloriesPerMinute: 5, instructions: ["Attach a rope to a high cable pulley and grip the ends with both hands. Push the rope down by extending your elbows, spreading the ends apart at the bottom. Slowly return to the starting position, keeping your elbows at your sides."] },
  { id: "skull-crushers", name: "Skull Crushers", category: "Triceps", muscleGroup: "Triceps", secondaryMuscles: ["Chest", "Front Delts"], equipment: "Barbell", caloriesPerMinute: 5.5, instructions: ["Lie on a flat bench holding a barbell or EZ bar with arms extended above your chest. Bend your elbows to lower the bar toward your forehead, keeping your upper arms stationary. Extend your arms back to the starting position."] },
  { id: "overhead-extension", name: "Overhead Tricep Extension", category: "Triceps", muscleGroup: "Triceps", secondaryMuscles: ["Shoulders"], equipment: "Dumbbells", caloriesPerMinute: 5, instructions: ["Hold a dumbbell with both hands behind your head, elbows pointing up. Extend your arms to press the dumbbell overhead until your arms are straight. Lower it back behind your head under control."] },
  { id: "overhead-cable-tricep-extension", name: "Overhead Cable Tricep Extension", category: "Triceps", muscleGroup: "Triceps", secondaryMuscles: ["Shoulders"], equipment: "Cable Machine", caloriesPerMinute: 5, instructions: ["Face away from a low cable pulley with a rope attachment held behind your head. Extend your arms overhead until fully straightened, keeping your elbows close to your head. Return to the starting position under control."] },
  { id: "tricep-dips", name: "Tricep Dips", category: "Triceps", muscleGroup: "Triceps", secondaryMuscles: ["Chest", "Front Delts"], equipment: "Bodyweight", caloriesPerMinute: 7, instructions: ["Grip parallel bars and support yourself with arms fully extended. Lower your body by bending your elbows until your upper arms are parallel to the floor, keeping your torso upright. Press back up to full extension."] },
  { id: "bench-dips", name: "Bench Dips", category: "Triceps", muscleGroup: "Triceps", secondaryMuscles: ["Chest", "Front Delts"], equipment: "Bodyweight", caloriesPerMinute: 6.5, instructions: ["Place your hands on the edge of a bench behind you with your legs extended forward. Lower your body by bending your elbows to about 90 degrees. Press back up to full arm extension."] },
  { id: "close-grip-bench", name: "Close Grip Bench Press", category: "Triceps", muscleGroup: "Triceps", secondaryMuscles: ["Chest", "Front Delts"], equipment: "Barbell", caloriesPerMinute: 7, instructions: ["Lie on a flat bench and grip the barbell with hands about shoulder-width apart. Lower the bar to your lower chest, keeping your elbows close to your body. Press the bar back up to lockout, focusing on your triceps."] },
  { id: "tricep-kickback", name: "Tricep Kickback", category: "Triceps", muscleGroup: "Triceps", secondaryMuscles: ["Rear Delts"], equipment: "Dumbbells", caloriesPerMinute: 4, instructions: ["Bend forward at the hips with a dumbbell in one hand and your upper arm parallel to the floor. Extend your forearm back until your arm is fully straight, squeezing your tricep. Lower back to the starting position and repeat."] },
  { id: "single-arm-cable-pushdown", name: "Single-Arm Cable Pushdown", category: "Triceps", muscleGroup: "Triceps", secondaryMuscles: ["Forearms"], equipment: "Cable Machine", caloriesPerMinute: 4.5, instructions: ["Attach a single handle to a high cable pulley. Push the handle down by extending your elbow, keeping your upper arm stationary. Slowly return to the starting position and complete all reps before switching arms."] },
  { id: "reverse-grip-cable-pushdown", name: "Reverse Grip Cable Pushdown", category: "Triceps", muscleGroup: "Triceps", secondaryMuscles: ["Forearms"], equipment: "Cable Machine", caloriesPerMinute: 4.5, instructions: ["Attach a straight bar to a high pulley and grip it with an underhand grip. Push the bar down by extending your elbows, keeping your upper arms at your sides. Return to the starting position under control."] },
  { id: "jm-press", name: "JM Press", category: "Triceps", muscleGroup: "Triceps", secondaryMuscles: ["Chest", "Front Delts"], equipment: "Barbell", caloriesPerMinute: 6, instructions: ["Lie on a flat bench and grip the bar at shoulder-width. Lower the bar toward your chin by bending your elbows, combining a skull crusher and close-grip bench motion. Press the bar back up to lockout."] },
  { id: "diamond-push-ups", name: "Diamond Push-Ups", category: "Triceps", muscleGroup: "Triceps", secondaryMuscles: ["Chest", "Front Delts"], equipment: "Bodyweight", caloriesPerMinute: 7, instructions: ["Get into a push-up position with your hands close together, forming a diamond shape with your thumbs and index fingers. Lower your chest toward your hands, keeping your elbows close to your body. Push back up to the starting position."] },

  // ================= LEGS =================
  { id: "squat", name: "Barbell Squat", category: "Legs", muscleGroup: "Quads", secondaryMuscles: ["Glutes", "Hamstrings", "Core"], equipment: "Barbell", caloriesPerMinute: 9, instructions: ["Place the barbell on your upper traps and stand with feet shoulder-width apart. Squat down by bending your knees and pushing your hips back until your thighs are at least parallel. Drive through your feet to stand back up."] },
  { id: "front-squat", name: "Front Squat", category: "Legs", muscleGroup: "Quads", secondaryMuscles: ["Glutes", "Core"], equipment: "Barbell", caloriesPerMinute: 9, instructions: ["Rest the barbell on the front of your shoulders with elbows pointing forward. Squat down while keeping your torso upright and elbows high. Drive through your heels to return to standing."] },
  { id: "goblet-squat", name: "Goblet Squat", category: "Legs", muscleGroup: "Quads", secondaryMuscles: ["Glutes", "Core"], equipment: "Dumbbells", caloriesPerMinute: 7, instructions: ["Hold a dumbbell vertically against your chest with both hands. Squat down between your legs, keeping your torso upright and elbows inside your knees. Stand back up by driving through your heels."] },
  { id: "sissy-squat", name: "Sissy Squat", category: "Legs", muscleGroup: "Quads", secondaryMuscles: ["Hip Flexors"], equipment: "Bodyweight", caloriesPerMinute: 6, instructions: ["Stand with feet shoulder-width apart, holding onto something for balance. Lean back and bend your knees forward while rising onto your toes. Lower until your thighs are near parallel, then squeeze your quads to return to standing."] },
  { id: "smith-machine-squat", name: "Smith Machine Squat", category: "Legs", muscleGroup: "Quads", secondaryMuscles: ["Glutes", "Hamstrings"], equipment: "Machine", caloriesPerMinute: 8, instructions: ["Position yourself under the Smith machine bar with it on your traps. Unrack and squat down until your thighs are parallel to the floor. Press back up to the starting position."] },
  { id: "hack-squat", name: "Hack Squat", category: "Legs", muscleGroup: "Quads", secondaryMuscles: ["Glutes"], equipment: "Machine", caloriesPerMinute: 8, instructions: ["Position your back against the pad with shoulders under the pads. Lower yourself by bending your knees until your thighs are parallel to the platform. Press back up through your heels."] },
  { id: "leg-press", name: "Leg Press", category: "Legs", muscleGroup: "Quads", secondaryMuscles: ["Glutes", "Hamstrings"], equipment: "Machine", caloriesPerMinute: 7.5, instructions: ["Sit in the leg press machine with feet shoulder-width apart on the platform. Lower the platform by bending your knees toward your chest. Press the platform back up without fully locking your knees."] },
  { id: "leg-extension", name: "Leg Extension", category: "Legs", muscleGroup: "Quads", secondaryMuscles: ["Hip Flexors"], equipment: "Machine", caloriesPerMinute: 5, instructions: ["Sit in the leg extension machine with the pad on your lower shins. Extend your legs until they are straight, squeezing your quads at the top. Lower the weight back down under control."] },
  { id: "seated-leg-curl", name: "Seated Leg Curl", category: "Legs", muscleGroup: "Hamstrings", secondaryMuscles: ["Calves"], equipment: "Machine", caloriesPerMinute: 5, instructions: ["Sit in the leg curl machine with the pad behind your lower legs. Curl your legs down and back by bending your knees, squeezing your hamstrings. Return to the starting position under control."] },
  { id: "romanian-deadlift", name: "Romanian Deadlift", category: "Legs", muscleGroup: "Hamstrings", secondaryMuscles: ["Glutes", "Lower Back"], equipment: "Barbell", caloriesPerMinute: 8, instructions: ["Stand holding a barbell at hip height with an overhand grip. Hinge at the hips and lower the bar along your legs, keeping a slight knee bend. Drive your hips forward to return to standing once you feel a hamstring stretch."] },
  { id: "db-rdl", name: "Dumbbell Romanian Deadlift", category: "Legs", muscleGroup: "Hamstrings", secondaryMuscles: ["Glutes", "Lower Back"], equipment: "Dumbbells", caloriesPerMinute: 7, instructions: ["Stand holding dumbbells in front of your thighs with arms straight. Hinge at the hips and lower the dumbbells along your legs, keeping your back flat and a slight knee bend. Drive your hips forward to return to standing when you feel a hamstring stretch."] },
  { id: "nordic-hamstring-curl", name: "Nordic Hamstring Curl", category: "Legs", muscleGroup: "Hamstrings", secondaryMuscles: ["Calves"], equipment: "Bodyweight", caloriesPerMinute: 7, instructions: ["Kneel on the floor with your feet anchored behind you. Slowly lower your body forward by extending at the knees, resisting gravity with your hamstrings. Use your hamstrings to pull yourself back up, or push off the floor to assist."] },
  { id: "glute-ham-raise", name: "Glute-Ham Raise", category: "Legs", muscleGroup: "Hamstrings", secondaryMuscles: ["Glutes", "Calves"], equipment: "Machine", caloriesPerMinute: 7, instructions: ["Position yourself in a GHD machine with feet secured and thighs against the pad. Lower your torso forward by extending at the knees while keeping your hips straight. Curl yourself back up using your hamstrings and glutes."] },
  { id: "sumo-deadlift", name: "Sumo Deadlift", category: "Legs", muscleGroup: "Glutes", secondaryMuscles: ["Quads", "Hamstrings", "Adductors", "Core"], equipment: "Barbell", caloriesPerMinute: 9, instructions: ["Stand with a very wide stance and toes pointed out, gripping the bar between your legs. Drive through the floor to stand up, pushing your hips forward. Lower the bar back to the floor with a controlled descent."] },
  { id: "trap-bar-deadlift", name: "Trap Bar Deadlift", category: "Legs", muscleGroup: "Glutes", secondaryMuscles: ["Quads", "Hamstrings", "Core", "Traps"], equipment: "Barbell", caloriesPerMinute: 9, instructions: ["Stand inside a trap bar and grip both handles. Drive through the floor to stand up, keeping your chest up and back flat. Lower the bar back down under control."] },
  { id: "lunges", name: "Lunges", category: "Legs", muscleGroup: "Quads", secondaryMuscles: ["Glutes", "Hamstrings"], equipment: "Dumbbells", caloriesPerMinute: 7, instructions: ["Stand holding dumbbells at your sides. Step forward with one leg and lower your back knee toward the floor until both knees are at 90 degrees. Push off your front foot to return to standing and alternate legs."] },
  { id: "bodyweight-lunge", name: "Bodyweight Lunge", category: "Legs", muscleGroup: "Quads", secondaryMuscles: ["Glutes", "Hamstrings"], equipment: "Bodyweight", caloriesPerMinute: 6, instructions: ["Stand tall with hands on your hips. Step forward with one leg and lower your back knee toward the floor until both knees are at roughly 90 degrees. Push off your front foot to return to standing and alternate legs."] },
  { id: "bodyweight-squat", name: "Bodyweight Squat", category: "Legs", muscleGroup: "Quads", secondaryMuscles: ["Glutes", "Core"], equipment: "Bodyweight", caloriesPerMinute: 5.5, instructions: ["Stand with feet shoulder-width apart and arms extended in front of you for balance. Squat down by pushing your hips back and bending your knees until your thighs are at least parallel to the floor. Drive through your heels to stand back up, squeezing your glutes at the top."] },
  { id: "walking-dumbbell-lunges", name: "Walking Dumbbell Lunges", category: "Legs", muscleGroup: "Quads", secondaryMuscles: ["Glutes", "Hamstrings"], equipment: "Dumbbells", caloriesPerMinute: 7.5, instructions: ["Hold dumbbells at your sides and step forward into a lunge. Lower your back knee toward the floor, then drive off your front foot to step into the next lunge. Continue walking forward, alternating legs."] },
  { id: "bulgarian-split", name: "Bulgarian Split Squat", category: "Legs", muscleGroup: "Quads", secondaryMuscles: ["Glutes", "Hamstrings"], equipment: "Dumbbells", caloriesPerMinute: 7.5, instructions: ["Stand about two feet in front of a bench and place one foot on it behind you. Holding dumbbells at your sides, lower your back knee toward the floor. Drive through your front foot to return to standing and complete all reps before switching."] },
  { id: "barbell-step-ups", name: "Barbell Step-Ups", category: "Legs", muscleGroup: "Quads", secondaryMuscles: ["Glutes", "Hamstrings"], equipment: "Barbell", caloriesPerMinute: 7.5, instructions: ["Place a barbell on your upper back and stand in front of a sturdy box or bench. Step up with one foot and drive through it to stand up fully. Step back down under control and alternate legs."] },
  { id: "calf-raise", name: "Calf Raise", category: "Legs", muscleGroup: "Calves", secondaryMuscles: ["Soleus"], equipment: "Machine", caloriesPerMinute: 4, instructions: ["Stand on a calf raise machine with the balls of your feet on the platform edge. Rise up onto your toes as high as possible, squeezing your calves at the top. Lower your heels below the platform for a full stretch."] },
  { id: "standing-calf-raise", name: "Standing Calf Raise", category: "Legs", muscleGroup: "Calves", secondaryMuscles: ["Soleus"], equipment: "Machine", caloriesPerMinute: 4, instructions: ["Stand on the platform of a standing calf raise machine with the balls of your feet on the edge. Rise onto your toes as high as possible, emphasising your gastrocnemius. Lower your heels below the platform for a full stretch and repeat."] },
  { id: "seated-calf-raise", name: "Seated Calf Raise", category: "Legs", muscleGroup: "Calves", secondaryMuscles: [], equipment: "Machine", caloriesPerMinute: 3.5, instructions: ["Sit in the seated calf raise machine with the pads on your lower thighs and the balls of your feet on the platform. Raise your heels as high as possible, squeezing your soleus at the top. Lower with control for a full stretch."] },
  { id: "donkey-calf-raise", name: "Donkey Calf Raise", category: "Legs", muscleGroup: "Calves", secondaryMuscles: ["Soleus"], equipment: "Machine", caloriesPerMinute: 4.5, instructions: ["Bend forward at the hips on a donkey calf raise machine with the pad on your lower back. Rise up onto your toes, squeezing your calves at the top. Lower your heels down for a deep stretch and repeat."] },
  { id: "hip-thrust", name: "Hip Thrust", category: "Legs", muscleGroup: "Glutes", secondaryMuscles: ["Hamstrings", "Core"], equipment: "Barbell", caloriesPerMinute: 7, instructions: ["Sit on the floor with your upper back against a bench. Place a barbell across your hips, feet flat on the floor. Drive through your heels to raise your hips until your body forms a straight line from shoulders to knees."] },
  { id: "glute-bridge", name: "Glute Bridge", category: "Legs", muscleGroup: "Glutes", secondaryMuscles: ["Hamstrings", "Core"], equipment: "Bodyweight", caloriesPerMinute: 4.5, instructions: ["Lie on your back with knees bent and feet flat on the floor, arms by your sides. Drive through your heels to lift your hips toward the ceiling, squeezing your glutes at the top. Lower back down under control and repeat."] },
  { id: "hip-abduction-machine", name: "Hip Abduction Machine", category: "Legs", muscleGroup: "Glutes", secondaryMuscles: ["Hip Flexors"], equipment: "Machine", caloriesPerMinute: 4.5, instructions: ["Sit in the hip abduction machine with the pads on the outside of your knees. Push your legs apart as far as possible, squeezing your outer glutes. Return to the starting position under control."] },
  { id: "hip-adduction-machine", name: "Hip Adduction Machine", category: "Legs", muscleGroup: "Adductors", secondaryMuscles: ["Glutes"], equipment: "Machine", caloriesPerMinute: 4.5, instructions: ["Sit in the hip adduction machine with the pads on the inside of your knees. Squeeze your legs together, engaging your inner thigh muscles. Slowly return to the starting position."] },
  { id: "cable-glute-kickback", name: "Cable Glute Kickback", category: "Legs", muscleGroup: "Glutes", secondaryMuscles: ["Hamstrings"], equipment: "Cable Machine", caloriesPerMinute: 4.5, instructions: ["Attach an ankle strap to a low cable and face the machine. Kick your leg straight back behind you, squeezing your glute at the top. Return under control and complete all reps before switching legs."] },
  { id: "pistol-squat", name: "Pistol Squats", category: "Legs", muscleGroup: "Quads", secondaryMuscles: ["Glutes", "Hamstrings", "Core"], equipment: "Bodyweight", caloriesPerMinute: 8, instructions: ["Stand on one leg with the other leg extended straight in front of you. Lower yourself into a deep squat on the standing leg, keeping your extended leg off the ground. Drive through your heel to stand back up and complete all reps before switching."] },

  // ================= CORE =================
  { id: "plank", name: "Plank", category: "Core", muscleGroup: "Core", secondaryMuscles: ["Shoulders", "Glutes"], equipment: "Bodyweight", caloriesPerMinute: 4, instructions: ["Get into a forearm plank position with elbows under your shoulders. Keep your body in a straight line from head to heels, engaging your core. Hold for the desired duration without letting your hips sag or pike."] },
  { id: "superman-hold", name: "Superman Hold", category: "Core", muscleGroup: "Lower Back", secondaryMuscles: ["Glutes", "Hamstrings"], equipment: "Bodyweight", caloriesPerMinute: 3.5, instructions: ["Lie face-down with arms extended overhead and legs straight. Lift your arms, chest, and legs off the floor by contracting your lower back and glutes. Hold briefly at the top, then lower back down under control."] },
  { id: "side-plank", name: "Side Plank", category: "Core", muscleGroup: "Obliques", secondaryMuscles: ["Core", "Shoulders"], equipment: "Bodyweight", caloriesPerMinute: 4, instructions: ["Lie on your side and prop yourself up on your forearm with elbow under your shoulder. Stack your feet and lift your hips, forming a straight line from head to feet. Hold for the desired duration, then switch sides."] },
  { id: "weighted-plank", name: "Weighted Plank", category: "Core", muscleGroup: "Core", secondaryMuscles: ["Shoulders", "Glutes"], equipment: "Bodyweight", caloriesPerMinute: 5, instructions: ["Get into a plank position and have a partner place a weight plate on your upper back. Maintain a rigid, straight body position with your core braced. Hold for the desired duration."] },
  { id: "crunches", name: "Crunches", category: "Core", muscleGroup: "Abs", secondaryMuscles: ["Hip Flexors"], equipment: "Bodyweight", caloriesPerMinute: 5, instructions: ["Lie on your back with knees bent and feet flat on the floor. Place your hands behind your head and curl your shoulders off the ground by contracting your abs. Lower back down with control and repeat."] },
  { id: "bicycle-crunch", name: "Bicycle Crunch", category: "Core", muscleGroup: "Obliques", secondaryMuscles: ["Abs"], equipment: "Bodyweight", caloriesPerMinute: 5.5, instructions: ["Lie on your back with hands behind your head and legs raised. Bring one knee toward your chest while rotating your torso to touch the opposite elbow to it. Alternate sides in a pedaling motion."] },
  { id: "decline-sit-up", name: "Decline Sit-Up", category: "Core", muscleGroup: "Abs", secondaryMuscles: ["Hip Flexors"], equipment: "Bodyweight", caloriesPerMinute: 5.5, instructions: ["Secure your feet at the top of a decline bench and lie back. Sit all the way up by contracting your abs, bringing your chest toward your knees. Lower yourself back down under control."] },
  { id: "leg-raise", name: "Hanging Leg Raise", category: "Core", muscleGroup: "Lower Abs", secondaryMuscles: ["Hip Flexors", "Core"], equipment: "Bodyweight", caloriesPerMinute: 6, instructions: ["Hang from a pull-up bar with arms fully extended. Raise your legs straight in front of you until they are parallel to the floor or higher. Lower them back down under control without swinging."] },
  { id: "toe-touches", name: "Toe Touches", category: "Core", muscleGroup: "Abs", secondaryMuscles: ["Hip Flexors"], equipment: "Bodyweight", caloriesPerMinute: 5, instructions: ["Lie on your back with legs extended straight up toward the ceiling. Reach your hands toward your toes by crunching your upper body off the floor. Lower back down and repeat."] },
  { id: "russian-twist", name: "Russian Twist", category: "Core", muscleGroup: "Obliques", secondaryMuscles: ["Abs", "Hip Flexors"], equipment: "Bodyweight", caloriesPerMinute: 5.5, instructions: ["Sit on the floor with knees bent and lean back slightly. Hold a weight or clasp your hands and rotate your torso from side to side. Keep your core engaged and feet off the ground for added difficulty."] },
  { id: "mountain-climbers", name: "Mountain Climbers", category: "Core", muscleGroup: "Core", secondaryMuscles: ["Shoulders", "Hip Flexors", "Quads"], equipment: "Bodyweight", caloriesPerMinute: 8, instructions: ["Start in a high plank position with hands under your shoulders. Drive one knee toward your chest, then quickly switch legs in a running motion. Keep your hips level and core tight throughout."] },
  { id: "cable-crunch", name: "Cable Crunch", category: "Core", muscleGroup: "Abs", secondaryMuscles: ["Obliques"], equipment: "Cable Machine", caloriesPerMinute: 5, instructions: ["Kneel in front of a high cable pulley with a rope attachment held behind your head. Crunch your torso down toward the floor by contracting your abs, bringing your elbows toward your knees. Return to the upright kneeling position under control."] },
  { id: "cable-woodchopper", name: "Cable Woodchopper", category: "Core", muscleGroup: "Obliques", secondaryMuscles: ["Core", "Shoulders"], equipment: "Cable Machine", caloriesPerMinute: 5, instructions: ["Set a cable to the highest position and grab the handle with both hands. Pull the handle diagonally across your body from high to low, rotating your torso. Return under control and complete all reps before switching sides."] },
  { id: "pallof-press", name: "Pallof Press", category: "Core", muscleGroup: "Core", secondaryMuscles: ["Obliques"], equipment: "Cable Machine", caloriesPerMinute: 4.5, instructions: ["Stand sideways to a cable machine and hold the handle at chest height with both hands. Press the handle straight out in front of you, resisting the rotational pull. Bring it back to your chest and repeat before switching sides."] },
  { id: "dead-bug", name: "Dead Bug", category: "Core", muscleGroup: "Core", secondaryMuscles: ["Hip Flexors"], equipment: "Bodyweight", caloriesPerMinute: 4, instructions: ["Lie on your back with arms toward the ceiling and knees bent at 90 degrees. Slowly extend one arm overhead while straightening the opposite leg, keeping your lower back on the floor. Return to start and alternate sides."] },
  { id: "dragon-flag", name: "Dragon Flag", category: "Core", muscleGroup: "Core", secondaryMuscles: ["Hip Flexors", "Lower Back"], equipment: "Bodyweight", caloriesPerMinute: 7, instructions: ["Lie on a bench and grip the edge behind your head. Raise your entire body vertically, then lower it as a rigid plank until nearly parallel to the bench. Keep your core braced and avoid bending at the hips."] },
  { id: "ab-wheel", name: "Ab Wheel Rollout", category: "Core", muscleGroup: "Core", secondaryMuscles: ["Lats", "Shoulders"], equipment: "Ab Wheel", caloriesPerMinute: 6, instructions: ["Kneel on the floor holding an ab wheel with both hands. Roll the wheel forward, extending your body as far as possible while keeping your core tight. Pull the wheel back toward your knees using your abs."] },
  { id: "l-sit", name: "L-Sit", category: "Core", muscleGroup: "Core", secondaryMuscles: ["Hip Flexors", "Triceps", "Shoulders"], equipment: "Bodyweight", caloriesPerMinute: 5.5, instructions: ["Support yourself on parallel bars or the floor with arms straight. Raise your legs in front of you until they are parallel to the ground, forming an L-shape. Hold this position with your core engaged for the desired duration."] },

  // ================= FULL BODY =================
  { id: "clean-and-press", name: "Clean and Press", category: "Full Body", muscleGroup: "Full Body", secondaryMuscles: ["Shoulders", "Legs", "Core"], equipment: "Barbell", caloriesPerMinute: 10, instructions: ["Start with the barbell on the floor. Pull it to your shoulders in one explosive motion (clean), then press it overhead. Lower back to shoulders, then to the floor and repeat."] },
  { id: "kettlebell-swing", name: "Kettlebell Swing", category: "Full Body", muscleGroup: "Full Body", secondaryMuscles: ["Glutes", "Hamstrings", "Core"], equipment: "Kettlebell", caloriesPerMinute: 10, instructions: ["Stand with feet shoulder-width apart, kettlebell between your feet. Hinge at the hips, grip the bell, and swing it forward by driving your hips. Let it swing to chest height, then control the descent."] },
  { id: "burpees", name: "Burpees", category: "Full Body", muscleGroup: "Full Body", secondaryMuscles: ["Chest", "Legs", "Core"], equipment: "Bodyweight", caloriesPerMinute: 10, instructions: ["From standing, drop into a squat with hands on the floor. Jump your feet back into a push-up position, perform a push-up, jump feet forward, then explode upward into a jump."] },
  { id: "thrusters", name: "Thrusters", category: "Full Body", muscleGroup: "Full Body", secondaryMuscles: ["Quads", "Shoulders", "Core"], equipment: "Barbell", caloriesPerMinute: 9.5, instructions: ["Hold the barbell at shoulder height in a front rack position. Squat down, then drive up explosively and press the bar overhead in one fluid movement. Lower and repeat."] },
  { id: "farmers-carry", name: "Farmer's Carry", category: "Full Body", muscleGroup: "Full Body", secondaryMuscles: ["Forearms", "Traps", "Core"], equipment: "Dumbbells", caloriesPerMinute: 9, instructions: ["Pick up heavy dumbbells or kettlebells in each hand. Stand tall with shoulders back and core braced. Walk forward with controlled steps, maintaining an upright posture throughout."] },
  { id: "sled-push-pull", name: "Sled Push/Pull", category: "Full Body", muscleGroup: "Full Body", secondaryMuscles: ["Quads", "Glutes", "Core"], equipment: "Machine", caloriesPerMinute: 10, instructions: ["For push: grip the sled handles at chest height and drive forward with powerful leg strides. For pull: attach a rope, face the sled, and pull it toward you hand over hand."] },
  { id: "landmine-squat", name: "Landmine Squat", category: "Full Body", muscleGroup: "Full Body", secondaryMuscles: ["Quads", "Glutes", "Core"], equipment: "Barbell", caloriesPerMinute: 8.5, instructions: ["Hold the end of a landmine barbell at chest height with both hands. Squat down keeping your torso upright, then drive through your heels to stand back up."] },
  { id: "zercher-squat", name: "Zercher Squat", category: "Full Body", muscleGroup: "Full Body", secondaryMuscles: ["Quads", "Glutes", "Biceps", "Core"], equipment: "Barbell", caloriesPerMinute: 9, instructions: ["Cradle the barbell in the crooks of your elbows with arms bent. Squat down keeping elbows inside your knees, maintaining an upright torso. Drive up through your heels."] },
  { id: "turkish-get-up", name: "Turkish Get-Up", category: "Full Body", muscleGroup: "Full Body", secondaryMuscles: ["Shoulders", "Core", "Glutes"], equipment: "Kettlebell", caloriesPerMinute: 8, instructions: ["Lie on your back holding a kettlebell straight up with one arm. Rise to a standing position through a series of controlled movements while keeping the weight overhead. Reverse the steps to return."] },
  { id: "man-maker", name: "Man Maker", category: "Full Body", muscleGroup: "Full Body", secondaryMuscles: ["Chest", "Shoulders", "Back", "Legs"], equipment: "Dumbbells", caloriesPerMinute: 11, instructions: ["Start in push-up position gripping dumbbells. Perform a push-up, row each dumbbell, jump feet to hands, clean the dumbbells to shoulders, then press overhead. Return to start."] },
  { id: "battle-ropes", name: "Battle Ropes", category: "Full Body", muscleGroup: "Full Body", secondaryMuscles: ["Shoulders", "Arms", "Core"], equipment: "Battle Ropes", caloriesPerMinute: 11, instructions: ["Hold one end of the rope in each hand. Create waves by alternating arms up and down rapidly, or slam both arms simultaneously. Keep a slight squat and engaged core throughout."] },
  { id: "box-jumps", name: "Box Jumps", category: "Full Body", muscleGroup: "Full Body", secondaryMuscles: ["Quads", "Glutes", "Calves"], equipment: "Box", caloriesPerMinute: 9, instructions: ["Stand facing a sturdy box. Swing your arms and jump explosively onto the box, landing softly with both feet. Stand fully upright, then step or jump back down and repeat."] },

  // ================= CARDIO =================
  { id: "treadmill", name: "Treadmill", category: "Cardio", muscleGroup: "Cardio", secondaryMuscles: ["Quads", "Calves"], equipment: "Machine", caloriesPerMinute: 10, instructions: ["Set your desired speed and incline. Walk or run at a steady pace, maintaining good posture with arms swinging naturally."] },
  { id: "incline-treadmill-walk", name: "Incline Treadmill Walking", category: "Cardio", muscleGroup: "Cardio", secondaryMuscles: ["Glutes", "Calves"], equipment: "Machine", caloriesPerMinute: 7, instructions: ["Set treadmill to a steep incline (10-15%). Walk at a moderate pace without holding the handrails. Keep your core engaged and lean slightly forward."] },
  { id: "elliptical", name: "Elliptical", category: "Cardio", muscleGroup: "Cardio", secondaryMuscles: ["Quads", "Glutes"], equipment: "Machine", caloriesPerMinute: 8, instructions: ["Stand on the pedals and grip the handles. Move in a smooth elliptical motion, pushing and pulling with both arms and legs."] },
  { id: "rowing-machine", name: "Rowing Machine", category: "Cardio", muscleGroup: "Cardio", secondaryMuscles: ["Back", "Legs", "Core"], equipment: "Machine", caloriesPerMinute: 9, instructions: ["Sit with feet strapped in and grip the handle. Drive through your legs first, then lean back and pull the handle to your chest. Return in reverse order."] },
  { id: "stairmaster", name: "Stairmaster", category: "Cardio", muscleGroup: "Cardio", secondaryMuscles: ["Quads", "Glutes", "Calves"], equipment: "Machine", caloriesPerMinute: 9, instructions: ["Step onto the machine and set your pace. Climb steadily without leaning on the handrails. Keep an upright posture throughout."] },
  { id: "bike", name: "Stationary Bike", category: "Cardio", muscleGroup: "Cardio", secondaryMuscles: ["Quads", "Hamstrings"], equipment: "Machine", caloriesPerMinute: 7.5, instructions: ["Adjust the seat height so your leg has a slight bend at the bottom. Pedal at a steady cadence, adjusting resistance as needed."] },
  { id: "spin-bike", name: "Spin Bike", category: "Cardio", muscleGroup: "Cardio", secondaryMuscles: ["Quads", "Hamstrings", "Core"], equipment: "Machine", caloriesPerMinute: 9, instructions: ["Set up the bike with proper seat and handlebar height. Pedal at high intensity, alternating between seated and standing positions."] },
  { id: "assault-bike", name: "Assault Bike", category: "Cardio", muscleGroup: "Cardio", secondaryMuscles: ["Full Body"], equipment: "Machine", caloriesPerMinute: 12, instructions: ["Grip both handles and place feet on pedals. Push and pull the handles while pedalling for a full-body cardio effort."] },
  { id: "ski-erg", name: "Ski Erg", category: "Cardio", muscleGroup: "Cardio", secondaryMuscles: ["Lats", "Core", "Triceps"], equipment: "Machine", caloriesPerMinute: 10, instructions: ["Stand facing the machine and grip both handles overhead. Pull down explosively while hinging at the hips, driving through your core and lats."] },
  { id: "jump-rope", name: "Jump Rope", category: "Cardio", muscleGroup: "Cardio", secondaryMuscles: ["Calves", "Shoulders"], equipment: "Jump Rope", caloriesPerMinute: 11, instructions: ["Hold handles at hip height with elbows close to your body. Swing the rope with your wrists and jump just high enough to clear it."] },
  { id: "swimming", name: "Swimming", category: "Cardio", muscleGroup: "Cardio", secondaryMuscles: ["Full Body"], equipment: "Pool", caloriesPerMinute: 9, instructions: ["Choose your stroke and swim continuous laps. Focus on breathing rhythm and maintaining a streamlined body position in the water."] },

  // ================= ADDITIONAL EXERCISES =================
  { id: "dips", name: "Dips", category: "Chest", muscleGroup: "Pectorals", secondaryMuscles: ["Triceps", "Front Delts"], equipment: "Bodyweight", caloriesPerMinute: 7.5, instructions: ["Grip parallel bars and support yourself with arms fully extended. Lower your body by bending your elbows, leaning slightly forward to emphasize the chest. Press back up to full arm extension once your upper arms are parallel to the floor."] },
  { id: "muscle-ups", name: "Muscle-Ups", category: "Full Body", muscleGroup: "Full Body", secondaryMuscles: ["Lats", "Chest", "Triceps", "Core"], equipment: "Bodyweight", caloriesPerMinute: 9.5, instructions: ["Hang from a pull-up bar with a false (thumbless) grip. Explosively pull yourself up and transition your chest over the bar by rolling your wrists forward. Press yourself up to full arm extension above the bar, then lower back to the hang."] },
  { id: "handstand-push-ups", name: "Handstand Push-Ups", category: "Shoulders", muscleGroup: "Deltoids", secondaryMuscles: ["Triceps", "Traps", "Core"], equipment: "Bodyweight", caloriesPerMinute: 8, instructions: ["Kick up into a handstand against a wall with your arms fully extended. Lower yourself by bending your elbows until the top of your head lightly touches the floor. Press back up to full arm extension, keeping your core tight and body straight."] },
  { id: "cable-fly", name: "Cable Fly", category: "Chest", muscleGroup: "Pectorals", secondaryMuscles: ["Front Delts"], equipment: "Cable Machine", caloriesPerMinute: 5.5, instructions: ["Set pulleys to chest height. Step forward with cables in each hand. Bring hands together in front of your chest with a slight bend in elbows, squeezing your chest at the peak."] },
];

export function getExercisesByCategory(category: string): Exercise[] {
  return EXERCISES.filter((e) => e.category === category);
}

export function getExerciseById(id: string): Exercise | undefined {
  return EXERCISES.find((e) => e.id === id);
}

export function estimateCalories(
  exerciseId: string,
  sets: number,
  reps: number,
  weightKg: number
): number {
  const exercise = getExerciseById(exerciseId);
  if (!exercise) return 0;
  const minutesPerSet = (reps * 3) / 60 + 1;
  const totalMinutes = minutesPerSet * sets;
  const weightMultiplier = 1 + (weightKg / 100) * 0.3;
  return Math.round(exercise.caloriesPerMinute * totalMinutes * weightMultiplier);
}
