/* GENERATED by `npm run art:cutouts` (scripts/art/cut-out-form-art.ts).
   Do not edit by hand: re-run the script when a reference frame changes.
   formArtCutouts.test.ts re-hashes every source and output listed here. */

export interface FormArtCutout {
  /** Public path of the transparent cut-out. */
  src: string;
  width: number;
  height: number;
  /** True when the black backdrop was keyed out; false when the set
   *  already carried its own alpha. */
  keyed: boolean;
  /** The released reference frame it was cut from. */
  source: string;
  sourceSha256: string;
  sha256: string;
}

export const FORM_ART_CUTOUTS: Record<string, FormArtCutout> = {
  "arnold-press": {
    src: "form-art/arnold-press.webp",
    width: 281,
    height: 480,
    keyed: true,
    source: "form-frames/arnold-press/3.webp",
    sourceSha256:
      "f2b4f69d46e29a5747105e51108f091311a393bbf670023186e5ff8bea5ba1ce",
    sha256: "4557236aa2ec2e78ad144ddd75a70670b4eec2bae464f666b159c1972b66f6ea",
  },
  "barbell-curl": {
    src: "form-art/barbell-curl.webp",
    width: 278,
    height: 480,
    keyed: true,
    source: "form-frames/barbell-curl/1.webp",
    sourceSha256:
      "88dbef553df593422a669d03a7f5a8573a293ebb668f1b9325d73b9aaec991b3",
    sha256: "53299754674650f2158af435ea4dd3a0fae4bd77a4f3e9c75aba73a94f6d2352",
  },
  "barbell-floor-press": {
    src: "form-art/barbell-floor-press.webp",
    width: 480,
    height: 295,
    keyed: true,
    source: "form-frames/barbell-floor-press/1.webp",
    sourceSha256:
      "b7a0180caae2adc778a5a9c28b7ba683cfea00d6337b27684c627fbd2615d900",
    sha256: "ba2daabf0f67d74024c2eb974ababf6a3a3fda9cfcb81669701dce370b79287f",
  },
  "barbell-row": {
    src: "form-art/barbell-row.webp",
    width: 282,
    height: 480,
    keyed: false,
    source: "form-frames/barbell-row/1.webp",
    sourceSha256:
      "6f514489bd36819239d4beab383cabf54140cf9d8b9115c1fe8995bab1093d10",
    sha256: "5a8b9821c205202b1acb5386e076d8c90fadc1aa845d749b22b628567351a9f5",
  },
  "barbell-shrug": {
    src: "form-art/barbell-shrug.webp",
    width: 278,
    height: 480,
    keyed: true,
    source: "form-frames/barbell-shrug/1.webp",
    sourceSha256:
      "6b0c887d9d7b07db7cb1820faa1e5a22567ac6d3f0aedc46882eefd8107ca554",
    sha256: "ba729705dee43819b3ce12c321b91e29abf454433ea125d00b5ce08ce574501d",
  },
  "barbell-upright-row": {
    src: "form-art/barbell-upright-row.webp",
    width: 416,
    height: 480,
    keyed: true,
    source: "form-frames/barbell-upright-row/3.webp",
    sourceSha256:
      "a0c2d040ea999078cc2ad37d8fccb37577a70f3849bf4a60fb4e7f6fc9aa634f",
    sha256: "b6f830ff75247d29c6e125a2b76743f1815dfbb2300354e7b64622362bcbbcf6",
  },
  "bench-dips": {
    src: "form-art/bench-dips.webp",
    width: 480,
    height: 387,
    keyed: true,
    source: "form-frames/bench-dips/1.webp",
    sourceSha256:
      "b93a52f52ccb2c14c1725fc474be516d8ea6b1eec35619aef599b13029f6b315",
    sha256: "98f2d0f28533de98bb345cf945af1d6773e1ec5914afae2349ef7244ce7d6cfb",
  },
  "bench-press": {
    src: "form-art/bench-press.webp",
    width: 480,
    height: 395,
    keyed: false,
    source: "form-frames/bench-press/1.webp",
    sourceSha256:
      "a7ec02db586a7f3a54fd801c40e12ab8dff11b386216e033516d40089ec3bc0f",
    sha256: "0a947b06f123aaf03f6489215fc9e38832932df52c671770d717905268ebcc09",
  },
  "bicycle-crunch": {
    src: "form-art/bicycle-crunch.webp",
    width: 480,
    height: 233,
    keyed: true,
    source: "form-frames/bicycle-crunch/3.webp",
    sourceSha256:
      "44f1530f3bbbe3aa0054d47736bf39c57fefce16a6a1d530ff10a3a194ab6256",
    sha256: "0754b36b79cfa413b81c194c38bd79f12e75f01041b3232e1b9aa6b32bd435db",
  },
  "bodyweight-squat": {
    src: "form-art/bodyweight-squat.webp",
    width: 243,
    height: 480,
    keyed: true,
    source: "form-frames/bodyweight-squat/1.webp",
    sourceSha256:
      "2c88d297b6b7a8c2d326eea2d98e7e313fc6c1d105fdb9bc3c8eb191cc6fdf00",
    sha256: "62ca3976d9beff700eef308f8a74185ca9925b91c7b46fbbf21788e72acdb9be",
  },
  "cable-crossover": {
    src: "form-art/cable-crossover.webp",
    width: 480,
    height: 318,
    keyed: true,
    source: "form-frames/cable-crossover/1.webp",
    sourceSha256:
      "2bf40fd0c782fd1b316e3dded539f2ab0564592bba09130deec7317c8cfceffc",
    sha256: "b264a3ed2fd2097391f81da147ca2f32144a6cce354a8bd1772d918a69cd587f",
  },
  "chest-press-machine": {
    src: "form-art/chest-press-machine.webp",
    width: 422,
    height: 480,
    keyed: true,
    source: "form-frames/chest-press-machine/1.webp",
    sourceSha256:
      "814f2db721603cb6c39f3bfb8053d38e35f9d6ee8388f872d902420bfc0e9f30",
    sha256: "743de2f9a7c0585e3d4c3f1c68eac55a21363e5857757ece539ea975133772ed",
  },
  "concentration-curl": {
    src: "form-art/concentration-curl.webp",
    width: 366,
    height: 480,
    keyed: true,
    source: "form-frames/concentration-curl/1.webp",
    sourceSha256:
      "02839e92a8a8c8a87ec5acfff9e21d292d94013b3123058fbba5513bf66898cf",
    sha256: "224311bcce309d5174467c68861c70f376f8917f94360d1b6f5912530e765600",
  },
  "cross-body-hammer-curl": {
    src: "form-art/cross-body-hammer-curl.webp",
    width: 201,
    height: 480,
    keyed: true,
    source: "form-frames/cross-body-hammer-curl/1.webp",
    sourceSha256:
      "a816ca65cc5c65cdf47dd993e3109ef23b498fbb8b5fb53c779a6917dee0a51b",
    sha256: "c4d32a6859859f09dd63f60e9eba9b4deae6a5b496d19c5e57962049ec23cd7d",
  },
  "db-bench": {
    src: "form-art/db-bench.webp",
    width: 480,
    height: 409,
    keyed: true,
    source: "form-frames/db-bench/1.webp",
    sourceSha256:
      "5a77b37330ccaf552f8f869a301f8bb8a6353982b60300a1464246499517bb9d",
    sha256: "cb0cd7a14d4a4087f0336387053bb5a4758a5dba1baf64f82b6ec47f580db6b8",
  },
  "db-curl": {
    src: "form-art/db-curl.webp",
    width: 209,
    height: 480,
    keyed: true,
    source: "form-frames/db-curl/1.webp",
    sourceSha256:
      "2fb3df52bdf690fe3873c6cb50022987089c9545b058322fff5737b70af4677c",
    sha256: "b03f35a236e20c54a98ce8c99f5d5d09ce8f5cdba7f61c927eb4a32d2e67d656",
  },
  "db-flyes": {
    src: "form-art/db-flyes.webp",
    width: 480,
    height: 386,
    keyed: true,
    source: "form-frames/db-flyes/1.webp",
    sourceSha256:
      "8566b8132276a66d97589e7b723667e364c494c7e273b50156c69cc09029d2a9",
    sha256: "9eac4364bffb20d6e981907e4fbc646568efac8b3d097b80c388bbacbb051983",
  },
  "dead-bug": {
    src: "form-art/dead-bug.webp",
    width: 480,
    height: 179,
    keyed: true,
    source: "form-frames/dead-bug/3.webp",
    sourceSha256:
      "a4724700049b2233a62439f44366dcc0b312483bd1171a8d93a8bec3963e5f5e",
    sha256: "a008d93007f511768e47bbc5dc20f3421e0c8082c22822ec4e151cac1a83be20",
  },
  "decline-bench": {
    src: "form-art/decline-bench.webp",
    width: 480,
    height: 254,
    keyed: true,
    source: "form-frames/decline-bench/3.webp",
    sourceSha256:
      "4fbfe76005d1c1803ef9e2f53d41e84487a23e79255e4a954c3d65b1860d2278",
    sha256: "0c6a530566b1048a50e8ea03a17cc37a398cfc6d91969b9bfb69968f347a64f8",
  },
  "decline-db-press": {
    src: "form-art/decline-db-press.webp",
    width: 480,
    height: 324,
    keyed: true,
    source: "form-frames/decline-db-press/1.webp",
    sourceSha256:
      "9d54d23d62841d5e150eb7b2de11825d725bc5aad28769e130a8e7f2ffe09844",
    sha256: "db625785fe3881704c1c38c356c21064331b7b857defbdf2505e869ffcf46a10",
  },
  "decline-sit-up": {
    src: "form-art/decline-sit-up.webp",
    width: 480,
    height: 247,
    keyed: true,
    source: "form-frames/decline-sit-up/1.webp",
    sourceSha256:
      "edc716815c85584cfbe9ec31caee14dd9a1b85a1d079bf60d18c1ad009f638f9",
    sha256: "a0458f04cbc823c6d07c1a6bff7923b349f76fff12bedeb42b5e2acf06edca22",
  },
  "diamond-push-ups": {
    src: "form-art/diamond-push-ups.webp",
    width: 480,
    height: 339,
    keyed: true,
    source: "form-frames/diamond-push-ups/1.webp",
    sourceSha256:
      "0b793f7680120af796a7fa721f1b09edd0a6b87a155bfe8e3bb697e13586cea2",
    sha256: "f495d7b8db1ff33c315d062948b43d7bd001247d1d5e00ff89ca72785d89df27",
  },
  dips: {
    src: "form-art/dips.webp",
    width: 339,
    height: 480,
    keyed: false,
    source: "form-frames/dips/1.webp",
    sourceSha256:
      "abd79b7a1788a4902a09f3709538df390a5c8b580761882fb9bb6244707be9f8",
    sha256: "335f739987f1a5ee6b8f513d243f475eaaf794fda16834e248aeef72d0fdfa55",
  },
  "ez-bar-curl": {
    src: "form-art/ez-bar-curl.webp",
    width: 297,
    height: 480,
    keyed: true,
    source: "form-frames/ez-bar-curl/1.webp",
    sourceSha256:
      "4812ee408e88da86a1fda7f80b03f0acd1c709d8ab6e49e4a43fa80878dca6e2",
    sha256: "39bd1d274b1c767d188867b23e4dfe77004783b58c7ea524fe16417780d15ffe",
  },
  "front-raise": {
    src: "form-art/front-raise.webp",
    width: 181,
    height: 480,
    keyed: true,
    source: "form-frames/front-raise/1.webp",
    sourceSha256:
      "c724267a05a39a4fd0b936de380bdd3dbc73accda8525d30607646a71a16bc79",
    sha256: "0c715bc608d077b8e093920e03091858565cbc7d59d62cde8b2be0cc7eedc1fc",
  },
  "glute-bridge": {
    src: "form-art/glute-bridge.webp",
    width: 480,
    height: 245,
    keyed: true,
    source: "form-frames/glute-bridge/1.webp",
    sourceSha256:
      "112bef9306be5708cbe718940077ca5f3e75c313ae42ee708975e10d1edc0c87",
    sha256: "90eb6cd307a3824ace8dfe44138d7b89318ad1f35843fd3428ce9e194de5b877",
  },
  "goblet-squat": {
    src: "form-art/goblet-squat.webp",
    width: 177,
    height: 480,
    keyed: true,
    source: "form-frames/goblet-squat/1.webp",
    sourceSha256:
      "18f7baa2fe3e599ff375db4140a0eeb5e015a5e945c35b85542d3503974d824a",
    sha256: "b6916ac7813c024fa7d102b18670fb9b8b3c87819082e7a7f97f9d52fc5adb17",
  },
  "hammer-curl": {
    src: "form-art/hammer-curl.webp",
    width: 192,
    height: 480,
    keyed: true,
    source: "form-frames/hammer-curl/1.webp",
    sourceSha256:
      "b4040f54ee8a8e4bfd02dd2867e085274386f6691084723d6cfd7aa62b701ebe",
    sha256: "17e58c8d8529b533bdd5b520c649e5baf621119465676b5bcb4a4add233b3ea8",
  },
  "incline-bench": {
    src: "form-art/incline-bench.webp",
    width: 480,
    height: 418,
    keyed: true,
    source: "form-frames/incline-bench/1.webp",
    sourceSha256:
      "bba515ce1ec06953de041e2d2ee71f41c1dbabe8321c4140c37b4e89556d9cb3",
    sha256: "dfbee104ef125836012cf0e3d4aa0fb078d30c875d914f940e69a6433f19f1ee",
  },
  "lateral-raise": {
    src: "form-art/lateral-raise.webp",
    width: 224,
    height: 480,
    keyed: true,
    source: "form-frames/lateral-raise/1.webp",
    sourceSha256:
      "2fc8466bb1c13bdeb4a8f1aa11fa4e62921e5fc9156bda5488c15d84416f4ea3",
    sha256: "594722a8afb61456e4b8ddcf7725e954cbde8a169049f28605fd520c5159e70c",
  },
  "lu-raise": {
    src: "form-art/lu-raise.webp",
    width: 210,
    height: 480,
    keyed: true,
    source: "form-frames/lu-raise/1.webp",
    sourceSha256:
      "424e07fb859cdc11275a169e4580a70ddcd9258d73499720cd8ecaf4b83f97cd",
    sha256: "ee4d9efb683965eeef530ff81a4b70037ae1abc8e5a426a58f27a5a29e4e681f",
  },
  "machine-chest-fly": {
    src: "form-art/machine-chest-fly.webp",
    width: 380,
    height: 480,
    keyed: true,
    source: "form-frames/machine-chest-fly/3.webp",
    sourceSha256:
      "b65f8b2e86ae81d78e972dab8398475892abde4aa409a24c326f3b0a659883ed",
    sha256: "28111ec20e951bb03db6bf0eae9985337abd95b3dbcf7a0068b452bd36b6546c",
  },
  "meadows-row": {
    src: "form-art/meadows-row.webp",
    width: 480,
    height: 319,
    keyed: true,
    source: "form-frames/meadows-row/1.webp",
    sourceSha256:
      "7961d3f929b80a28138331d0db65d2cdf67f4289e0306ced4942b4e859564c61",
    sha256: "b3775480a78cc4655961983ca497f8189d7a80f781443933c3e0c00cd127daaa",
  },
  "overhead-press": {
    src: "form-art/overhead-press.webp",
    width: 480,
    height: 437,
    keyed: false,
    source: "form-frames/overhead-press/1.webp",
    sourceSha256:
      "7791e3042759ae61f30aff4b97bfbfecce1c412adcee6d8edb493cb400782eae",
    sha256: "db6cc312a0378873892d4c9306ea7791f484844c9fbd04d487d014661da7ae29",
  },
  "pec-deck": {
    src: "form-art/pec-deck.webp",
    width: 414,
    height: 480,
    keyed: true,
    source: "form-frames/pec-deck/1.webp",
    sourceSha256:
      "d831f34f8cb92b1d1a6de8b08ea2d8d3aa5273476eafeecbecc7e8fb0afb7b59",
    sha256: "dbbec23e6cc9e8a10b3e730e41c704a221af15eb3511c814c5b28defd827bc76",
  },
  "pike-push-up": {
    src: "form-art/pike-push-up.webp",
    width: 480,
    height: 319,
    keyed: true,
    source: "form-frames/pike-push-up/1.webp",
    sourceSha256:
      "70aed55136f54a96e8ba3c000361c13104b984c5d68b379158ad59d00a823a26",
    sha256: "f7f5a025471cdd0c125376f9ec2d937183976f02a6c1514ecec4be33c7a9f5d3",
  },
  "push-ups": {
    src: "form-art/push-ups.webp",
    width: 480,
    height: 304,
    keyed: true,
    source: "form-frames/push-ups/1.webp",
    sourceSha256:
      "5639a5655874f8e6378faebe5b928e102fc11cdb42bb72a56c2aa22e5c39dbb6",
    sha256: "3cafc7d77f0a2bd0a005734221616079c020eb63a347f5769c5f0ecb420787c7",
  },
  "reverse-barbell-curl": {
    src: "form-art/reverse-barbell-curl.webp",
    width: 315,
    height: 480,
    keyed: true,
    source: "form-frames/reverse-barbell-curl/1.webp",
    sourceSha256:
      "529b0144bb430c610bf0c55281ce32df417e3a62bbddad887a8fda5c9b9ffcfb",
    sha256: "78ead36685afc28603ae7c2057a7566ddbbc9a13c0302fc79677f33af636632f",
  },
  "rope-tricep-pushdown": {
    src: "form-art/rope-tricep-pushdown.webp",
    width: 272,
    height: 480,
    keyed: false,
    source: "form-frames/rope-tricep-pushdown/1.webp",
    sourceSha256:
      "a177e100adc921d2741d6e7fcb68ffd67c8f0604105ee78d6c20f6b05f2f4cba",
    sha256: "5b4d852abbd3033f9d785107093ff6d8f9765b00fd2e179844de358f681f809e",
  },
  "russian-twist": {
    src: "form-art/russian-twist.webp",
    width: 480,
    height: 291,
    keyed: true,
    source: "form-frames/russian-twist/4.webp",
    sourceSha256:
      "d76a8cb29e043fb367a192c4f1a129c6bcfdf6b595564235cd910bf0322293e9",
    sha256: "f14c2f0a93d6e57f82ca4535c347a57479599d316229df0b716ff28ce0006c23",
  },
  "skull-crushers": {
    src: "form-art/skull-crushers.webp",
    width: 480,
    height: 436,
    keyed: false,
    source: "form-frames/skull-crushers/1.webp",
    sourceSha256:
      "b5e8eb9e7c552413d557c53f61aa9948f8674ae1debdcf987f5aeaa696b7fcfa",
    sha256: "2a48e80837ebeba858632f2d37fddd055ddd891888dedf6105b2c2bfe9c5930a",
  },
  "spider-db-curl": {
    src: "form-art/spider-db-curl.webp",
    width: 471,
    height: 480,
    keyed: true,
    source: "form-frames/spider-db-curl/1.webp",
    sourceSha256:
      "3c174a2b0e9c5605f8af0f28427bbca75891e3b41f1afac085e172f704ef9bf2",
    sha256: "68cd8e60ef3a708c7b444ed97fa7eacb0b46e4c3c7519a3d03db82807b30656d",
  },
  squat: {
    src: "form-art/squat.webp",
    width: 315,
    height: 480,
    keyed: true,
    source: "form-frames/squat/1.webp",
    sourceSha256:
      "be48eb2d8d92308fc4e4d72c7509915d87a6b8efe0fba68500cf7c1721882cfe",
    sha256: "4186733dbe706284d7a215248f04aca16975fc7087f59da551de06c8da9bfc03",
  },
  "superman-hold": {
    src: "form-art/superman-hold.webp",
    width: 480,
    height: 213,
    keyed: true,
    source: "form-frames/superman-hold/1.webp",
    sourceSha256:
      "99565c667a11afdaf06170564f23d6f71f4be04bd05bbf5de3547f98fe3d7ca4",
    sha256: "b9d0f02faf0f20f0b749814f395699fd73586d9ac16ee06b5c76198bdf78717b",
  },
  "toe-touches": {
    src: "form-art/toe-touches.webp",
    width: 480,
    height: 310,
    keyed: true,
    source: "form-frames/toe-touches/1.webp",
    sourceSha256:
      "cfaee4b9b2bccd321f65af5349abb3c14be80c8472e700323a0b130a3dedf793",
    sha256: "469cc238ac34dbaa628d867ab8c6f2bbfb40881d4e1454f15371fa0889a9c998",
  },
  "tricep-kickback": {
    src: "form-art/tricep-kickback.webp",
    width: 480,
    height: 474,
    keyed: true,
    source: "form-frames/tricep-kickback/1.webp",
    sourceSha256:
      "4a040d5f7ad81019320c56eb16496e6b0ddc43111da97c67e672509d22d67cb4",
    sha256: "0793176a293774f3aa56e6e285a8edf6632b3915b8085204d52681c735cda6e0",
  },
  "weighted-chest-dip": {
    src: "form-art/weighted-chest-dip.webp",
    width: 383,
    height: 480,
    keyed: true,
    source: "form-frames/weighted-chest-dip/1.webp",
    sourceSha256:
      "36c7e31ed1727d6222035b72747299bf7c36ec84269ea57673384e24321167f8",
    sha256: "e4e27d65259672a0317a3c0d316a7f19365dfbf233d8cc529f0bf7084ac24dd6",
  },
  "weighted-push-ups": {
    src: "form-art/weighted-push-ups.webp",
    width: 480,
    height: 294,
    keyed: true,
    source: "form-frames/weighted-push-ups/1.webp",
    sourceSha256:
      "621f3efee49e900e99a31fb5d3a9c4d8ab08f93bb4479d00c03427781f41b9d7",
    sha256: "03ed2e2e5e8ae6f8e6a938dc9750488fce7c42ad810cabeebf2dcdf44553ec65",
  },
  "zottman-curl": {
    src: "form-art/zottman-curl.webp",
    width: 220,
    height: 480,
    keyed: true,
    source: "form-frames/zottman-curl/1.webp",
    sourceSha256:
      "fec9ddba08bf82cc35bd798db84c03fbcd850dcc42ddfbb0f430a07621e1d7ae",
    sha256: "459c8838248ffaeba5f7ef80fa831674290a26dbb69f64ceceae5d8045138659",
  },
};
