/**
 * The source of src/lib/formArtCutouts.data.ts, as `npm run art:cutouts`
 * writes it. Kept apart from the generator, which cuts images when it is
 * imported, so cutout-manifest.test.ts can hold the committed file to it.
 */
import type { FormArtCutout } from "../../src/lib/formArtCutouts.data";

export const CUTOUT_MANIFEST = "src/lib/formArtCutouts.data.ts";

/** The manifest's source, before formatting, with one row per cut-out in
 *  the order given: the generator gives them in exercise-ID order. */
export function renderCutoutManifest(
  rows: readonly (readonly [string, FormArtCutout])[]
): string {
  const lines = rows.map(
    ([id, cutout]) =>
      `  ${JSON.stringify(id)}: { src: ${JSON.stringify(cutout.src)}, width: ${cutout.width}, height: ${cutout.height}, keyed: ${cutout.keyed}, source: ${JSON.stringify(cutout.source)}, sourceSha256: ${JSON.stringify(cutout.sourceSha256)}, sha256: ${JSON.stringify(cutout.sha256)} },`
  );
  return `/* GENERATED by \`npm run art:cutouts\` (scripts/art/cut-out-form-art.ts).
   Do not edit by hand: re-run the script when a reference frame changes.
   formArtCutouts.test.ts re-hashes every source and output listed here. */

export interface FormArtCutout {
  /** Public path of the transparent cut-out. */
  src: string;
  width: number;
  height: number;
  /** True when the black backdrop was keyed out; false when the reviewed
   *  input already carried its own alpha. */
  keyed: boolean;
  /** The released reference frame it was cut from. */
  source: string;
  sourceSha256: string;
  sha256: string;
}

export const FORM_ART_CUTOUTS: Record<string, FormArtCutout> = {
${lines.join("\n")}
};
`;
}
