/**
 * The approved releases are built from their records, and only from them.
 *
 * src/lib/formArtReleases.data.ts is generated by `npm run art:releases`.
 * This holds the committed file to exactly what the generator would write
 * from today's records, so a record added without regenerating, or a row
 * edited by hand, fails here rather than shipping a set that differs from
 * its review.
 */
import { readFileSync } from "node:fs";
import { resolve } from "node:path";
import { describe, expect, it } from "vitest";
import { formatGenerated } from "./format-generated";
import {
  approvedReleases,
  readReleaseRecords,
  renderReleasesModule,
  RELEASES_MODULE,
  type ReleaseRecordFile,
} from "./form-art-releases";

const ROOT = process.cwd();

/** An approved record for `id`, reviewed at noon on `day`. */
function record(
  id: string,
  day: string,
  changes: Record<string, unknown> = {}
): ReleaseRecordFile {
  return {
    folder: day,
    name: id,
    record: {
      exerciseId: id,
      version: `anatomy-v3-${day}`,
      width: 1024,
      height: 1536,
      decision: "approved",
      reviewedAt: `${day}T12:00:00.000Z`,
      reference: { path: `form-frames/${id}/3.webp`, sha256: "a".repeat(64) },
      frames: Array.from({ length: 6 }, (_, i) => ({
        path: `form-frames/${id}/${i + 1}.webp`,
        sha256: "a".repeat(64),
      })),
      ...changes,
    },
  };
}

describe("approved artwork releases", () => {
  it("are generated from today's release records", async () => {
    const path = resolve(ROOT, RELEASES_MODULE);
    const expected = await formatGenerated(
      path,
      renderReleasesModule(approvedReleases(readReleaseRecords(ROOT)))
    );
    expect(
      readFileSync(path, "utf8") === expected,
      `${RELEASES_MODULE} is not what the release records say: run npm run art:releases`
    ).toBe(true);
  });

  it("read the records and not the evidence kept beside them", () => {
    const records = readReleaseRecords(ROOT);
    expect(new Set(records.map(({ record }) => record.decision))).toEqual(
      new Set(["approved", "owner-released-with-findings"])
    );
    expect(
      records.filter(({ name }) => /provenance|validation/i.test(name))
    ).toEqual([]);
  });

  it("take each set's newest approved record, whatever order they are read in", () => {
    const records = [
      record("db-curl", "2026-09-29"),
      record("db-curl", "2026-10-05", {
        reference: { path: "form-frames/db-curl/1.webp" },
      }),
      // Neither a draft nor an owner release is an approval, however new.
      record("db-curl", "2026-10-07", { decision: "draft" }),
      record("squat", "2026-09-30", {
        decision: "owner-released-with-findings",
        reviewedAt: undefined,
      }),
      record("arnold-press", "2026-09-24"),
    ];
    const expected = {
      "arnold-press": {
        folder: "2026-09-24",
        version: "anatomy-v3-2026-09-24",
        width: 1024,
        height: 1536,
        reference: 3,
      },
      "db-curl": {
        folder: "2026-10-05",
        version: "anatomy-v3-2026-10-05",
        width: 1024,
        height: 1536,
        reference: 1,
      },
    };
    expect(approvedReleases(records)).toEqual(expected);
    expect(Object.keys(approvedReleases(records))).toEqual([
      "arnold-press",
      "db-curl",
    ]);
    expect(approvedReleases([...records].reverse())).toEqual(expected);
  });

  it("refuse a record they could not build a release from", () => {
    const frames = record("db-curl", "2026-09-29").record.frames as {
      path: string;
    }[];
    const cases: [ReleaseRecordFile[], RegExp][] = [
      [
        [{ ...record("db-curl", "2026-09-29"), name: "db-curls" }],
        /named for its exerciseId/,
      ],
      [[record("db-curl", "2026-09-29", { reviewedAt: "" })], /review date/],
      [
        [record("db-curl", "2026-09-29", { frames: [...frames].reverse() })],
        /frames/,
      ],
      [
        [record("db-curl", "2026-09-29", { frames: frames.slice(0, 5) })],
        /frames/,
      ],
      [
        [
          record("db-curl", "2026-09-29", {
            frames: record("squat", "2026-09-29").record.frames,
          }),
        ],
        /frames/,
      ],
      [
        [
          record("db-curl", "2026-09-29", {
            reference: { path: "form-frames/db-curl/7.webp" },
          }),
        ],
        /reference/,
      ],
      [
        [record("db-curl", "2026-09-29", { reference: undefined })],
        /reference/,
      ],
      [
        [record("db-curl", "2026-09-29", { version: " " })],
        /version, width and height/,
      ],
      [
        [record("db-curl", "2026-09-29", { width: "1024" })],
        /version, width and height/,
      ],
      [
        [record("db-curl", "2026-09-29", { height: 0 })],
        /version, width and height/,
      ],
      [
        [
          record("db-curl", "2026-09-29"),
          { ...record("db-curl", "2026-09-29"), folder: "2026-09-30" },
        ],
        /share a review date/,
      ],
    ];
    for (const [records, error] of cases)
      expect(() => approvedReleases(records), String(error)).toThrow(error);
  });
});
